import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Ban, CheckCircle2, ClipboardList, Edit3, Eye, LoaderCircle, Plus, Search, UserRoundCheck, X } from 'lucide-react';
import API_ENDPOINTS from '../../config/endpoints.js';
import ResourceService from '../../services/ResourceService.jsx';
import { useToast } from '../../context/ToastContext.jsx';
import getApiErrorMessage from '../../utils/apiError.js';
import { formatDateTimeDisplay } from '../../utils/dateFormat.js';
import '../../style/GraduationEnrollment.scss';
import '../../style/EnrollmentStudentList.scss';

const STATUS = { ELIGIBLE:'Chờ phê duyệt', ENROLLED:'Đã ghi danh', IN_PROGRESS:'Đang thực hiện', COMPLETED:'Đã hoàn thành', FAILED:'Không đạt', WITHDRAWN:'Bị cấm bảo vệ' };
const NEXT = { ELIGIBLE:['ENROLLED'], ENROLLED:['IN_PROGRESS'], IN_PROGRESS:['COMPLETED','FAILED'], COMPLETED:['FAILED'], FAILED:['COMPLETED'], WITHDRAWN:[] };

export default function GraduationEnrollmentPage({ mode = 'admin' }) {
  const studentMode = mode === 'student'; const toast = useToast();
  const [items,setItems]=useState([]); const [students,setStudents]=useState([]); const [periods,setPeriods]=useState([]); const [teams,setTeams]=useState([]); const [topics,setTopics]=useState([]);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [periodId,setPeriodId]=useState(''); const [modal,setModal]=useState(null);
  const [studentSearch,setStudentSearch]=useState('');
  const [form,setForm]=useState({studentCodes:[],academicYearId:'',defensePeriodId:'',status:'ENROLLED',note:''});
  const load=async()=>{setLoading(true);setError('');try{if(studentMode){setItems(await ResourceService.getOne(API_ENDPOINTS.graduationEnrollments.mine));}else{const [enrollments,studentList,periodList,teamList,topicList]=await Promise.all([ResourceService.getAll(API_ENDPOINTS.graduationEnrollments.list,{size:500}),ResourceService.getAll(API_ENDPOINTS.students.list,{size:500}),ResourceService.getAll(API_ENDPOINTS.defensePeriods.list,{size:500}),ResourceService.getAll(API_ENDPOINTS.teams.list,{size:500}),ResourceService.getAll(API_ENDPOINTS.topics.list,{size:500})]);setItems(enrollments);setStudents(studentList);setPeriods(periodList);setTeams(teamList);setTopics(topicList);}}catch(e){setError(getApiErrorMessage(e,'Không thể tải hồ sơ ghi danh.'));}finally{setLoading(false);}};
  useEffect(()=>{load();},[mode]); // eslint-disable-line react-hooks/exhaustive-deps
  const teamPeriodById=useMemo(()=>{const topicPeriods=new Map(topics.map(topic=>[String(topic.topicId),topic.defensePeriodId]));return new Map(teams.map(team=>[String(team.idTeam),topicPeriods.get(String(team.topicId))]));},[teams,topics]);
  const studentsWithTeam=useMemo(()=>students.filter(student=>student.teamId!=null||student.idTeam!=null).map(student=>({...student,defensePeriodId:teamPeriodById.get(String(student.teamId??student.idTeam))})),[students,teamPeriodById]);
  const academicYears=useMemo(()=>{const years=new Map();periods.forEach(period=>{const id=period.academicId??period.academicYearId??period.academicYear;if(id!=null&&!years.has(String(id)))years.set(String(id),{id,label:period.academicYear||String(id)});});return [...years.values()].sort((a,b)=>a.label.localeCompare(b.label));},[periods]);
  const filtered=useMemo(()=>items.filter(i=>(!status||i.status===status)&&(!periodId||String(i.defensePeriodId)===String(periodId))&&`${i.studentName} ${i.studentCode} ${i.defensePeriodName} ${i.teamName||''}`.toLowerCase().includes(query.toLowerCase())),[items,status,periodId,query]);
  const create=async(e)=>{e.preventDefault();if(!form.studentCodes.length)return;setSaving(true);setError('');try{await ResourceService.create(API_ENDPOINTS.graduationEnrollments.bulkCreate,{studentCodes:form.studentCodes,defensePeriodId:Number(form.defensePeriodId),note:form.note||null});toast.success(`Đã ghi danh ${form.studentCodes.length} sinh viên vào đợt bảo vệ.`);setModal(null);await load();}catch(err){setError(getApiErrorMessage(err,'Không thể ghi danh danh sách sinh viên.'));}finally{setSaving(false);}};
  const update=async(e)=>{e.preventDefault();setSaving(true);setError('');try{await ResourceService.update(API_ENDPOINTS.graduationEnrollments.update(modal.item.enrollmentId),{status:form.status,note:form.note||null},'patch');toast.success('Đã cập nhật hồ sơ ghi danh.');setModal(null);await load();}catch(err){setError(getApiErrorMessage(err,'Không thể cập nhật ghi danh.'));}finally{setSaving(false);}};
  const withdraw=async(item)=>{if(!window.confirm(`Hủy tư cách thi của ${item.studentName} trong ${item.defensePeriodName}? Sinh viên sẽ bị khóa thao tác và nhận điểm 0.`))return;setSaving(true);setError('');try{await ResourceService.update(API_ENDPOINTS.graduationEnrollments.withdraw(item.enrollmentId),null,'patch');toast.success(`${item.studentName} đã bị hủy tư cách thi trong ${item.defensePeriodName}.`);await load();}catch(err){setError(getApiErrorMessage(err,'Không thể hủy tư cách thi.'));}finally{setSaving(false);}};
  const openCreate=()=>{setForm({studentCodes:[],academicYearId:'',defensePeriodId:'',status:'ENROLLED',note:''});setStudentSearch('');setError('');setModal({type:'create'});};
  const openEdit=(item)=>{setForm({status:item.status,note:item.note||''});setError('');setModal({type:'edit',item});};
  return <div className="enrollment-page"><div className="page-heading"><div><span>QUẢN LÝ ĐỒ ÁN</span><h1>{studentMode?'Hồ sơ ghi danh đồ án':'Ghi danh đồ án tốt nghiệp'}</h1><p>{studentMode?'Theo dõi đợt bảo vệ và trạng thái tham gia của bạn.':'Ghi danh sinh viên vào đợt bảo vệ.'}</p></div>{!studentMode&&<button className="primary-button" onClick={openCreate}><Plus size={17}/> Ghi danh sinh viên</button>}</div>{error&&<div className="workflow-error"><AlertCircle size={16}/>{error}</div>}
  {!studentMode&&<section className="enrollment-summary"><article><UserRoundCheck/><div><span>Tổng ghi danh</span><strong>{items.filter(i=>!['ELIGIBLE','WITHDRAWN'].includes(i.status)).length}</strong></div></article><article><ClipboardList/><div><span>Đang thực hiện</span><strong>{items.filter(i=>['ENROLLED','IN_PROGRESS'].includes(i.status)).length}</strong></div></article><article><CheckCircle2/><div><span>Đã hoàn thành</span><strong>{items.filter(i=>i.status==='COMPLETED').length}</strong></div></article></section>}
  <section className="enrollment-panel">{!studentMode&&<div className="enrollment-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo sinh viên, nhóm hoặc đợt bảo vệ..."/></label><select value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">Tất cả đợt bảo vệ</option>{periods.map(p=><option key={p.defensePeriodId} value={p.defensePeriodId}>{p.periodName} · {p.academicYear}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}{loading?<State/>:filtered.length?<div className="enrollment-table"><table><thead><tr><th>Sinh viên</th><th>Đợt bảo vệ</th><th>Nhóm</th><th>Ngày ghi danh</th><th>Trạng thái</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.enrollmentId}><td><strong>{item.studentName}</strong><small>{item.studentCode} · {item.classCode||'Chưa xếp lớp'}</small></td><td><strong>{item.defensePeriodName}</strong><small>{item.academicYear}</small></td><td>{item.teamName||'Chưa có nhóm'}</td><td>{formatDate(item.enrolledAt)}</td><td><span className={`enrollment-status ${item.status.toLowerCase()}`}>{STATUS[item.status]||item.status}</span></td><td><div className="enrollment-actions"><button title="Xem chi tiết" onClick={()=>setModal({type:'detail',item})}><Eye size={15}/></button>{!studentMode&&item.status!=='WITHDRAWN'&&<><button title="Cập nhật" onClick={()=>openEdit(item)}><Edit3 size={15}/></button><button className="danger" title="Hủy tư cách thi" disabled={saving} onClick={()=>withdraw(item)}><Ban size={15}/></button></>}</div></td></tr>)}</tbody></table></div>:<div className="enrollment-empty"><ClipboardList/><strong>Chưa có hồ sơ ghi danh phù hợp.</strong></div>}</section>
  {modal&&<div className="modal-backdrop"><section className="enrollment-modal"><header><div><span>{modal.type==='create'?'GHI DANH MỚI':modal.type==='edit'?'CẬP NHẬT GHI DANH':'CHI TIẾT GHI DANH'}</span><h3>{modal.item?.studentName||'Sinh viên đồ án'}</h3></div><button onClick={()=>setModal(null)}><X/></button></header>{modal.type==='detail'?<EnrollmentDetail item={modal.item}/>:<form onSubmit={modal.type==='create'?create:update}>{modal.type==='create'?<><StudentMultiSelect students={studentsWithTeam} enrollments={items} periodId={form.defensePeriodId} selected={form.studentCodes} query={studentSearch} onQuery={setStudentSearch} onChange={studentCodes=>setForm({...form,studentCodes})}/><label>Năm học<b>*</b><select required value={form.academicYearId} onChange={e=>setForm({...form,academicYearId:e.target.value,defensePeriodId:'',studentCodes:[]})}><option value="">Chọn năm học</option>{academicYears.map(year=><option key={year.id} value={year.id}>{year.label}</option>)}</select></label><label>Đợt bảo vệ<b>*</b><select required disabled={!form.academicYearId} value={form.defensePeriodId} onChange={e=>setForm({...form,defensePeriodId:e.target.value,studentCodes:[]})}><option value="">{form.academicYearId?'Chọn đợt bảo vệ':'Chọn năm học trước'}</option>{periods.filter(p=>p.status!=='FINISHED'&&String(p.academicId??p.academicYearId)===String(form.academicYearId)).map(p=><option key={p.defensePeriodId} value={p.defensePeriodId}>{p.periodName}</option>)}</select></label></>:<label>Trạng thái<b>*</b><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value={modal.item.status}>{STATUS[modal.item.status]}</option>{NEXT[modal.item.status].map(v=><option key={v} value={v}>{STATUS[v]}</option>)}</select></label>}<label className="wide">Ghi chú<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Thông tin bổ sung cho hồ sơ ghi danh..."/></label>{error&&<div className="workflow-error"><AlertCircle size={16}/>{error}</div>}<footer><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Hủy</button><button className="primary-button" disabled={saving||(modal.type==='create'&&!form.studentCodes.length)}>{saving?'Đang lưu...':modal.type==='create'?`Ghi danh ${form.studentCodes.length} sinh viên`:'Lưu dữ liệu'}</button></footer></form>}</section></div>}</div>;
}
function StudentMultiSelect({students,enrollments,periodId,selected,query,onQuery,onChange}){const enrolled=new Set(enrollments.filter(i=>String(i.defensePeriodId)===String(periodId)).map(i=>i.studentCode));const periodStudents=periodId?students.filter(s=>String(s.defensePeriodId)===String(periodId)):students;const filtered=periodStudents.filter(s=>`${s.fullName} ${s.studentCode} ${s.teamName||''}`.toLowerCase().includes(query.toLowerCase()));const availableCodes=periodStudents.filter(s=>!enrolled.has(s.studentCode)).map(s=>s.studentCode);const allSelected=availableCodes.length>0&&availableCodes.every(code=>selected.includes(code));const toggle=code=>onChange(selected.includes(code)?selected.filter(v=>v!==code):[...selected,code]);const toggleAll=()=>onChange(allSelected?selected.filter(code=>!availableCodes.includes(code)):[...new Set([...selected,...availableCodes])]);return <div className="student-multi"><div className="student-multi-title"><span>Danh sách sinh viên <b>*</b></span><div className="student-multi-actions"><strong>Đã chọn {selected.length}</strong><button type="button" disabled={!periodId||!availableCodes.length} onClick={toggleAll}>{allSelected?'Bỏ chọn toàn bộ':'Chọn toàn bộ'}</button></div></div><p className="student-multi-hint">{periodId?'Chỉ hiển thị sinh viên thuộc nhóm có đề tài trong đợt đã chọn.':'Chọn năm học và đợt bảo vệ để lọc sinh viên; hiện chỉ cho phép chọn sinh viên đã xếp nhóm.'}</p><label className="student-list-search"><Search size={16}/><input value={query} onChange={e=>onQuery(e.target.value)} placeholder="Tìm theo tên hoặc mã sinh viên..."/></label><div className="student-check-list">{filtered.length?filtered.map(s=>{const disabled=!periodId||enrolled.has(s.studentCode);return <label key={s.studentCode} className={disabled?'disabled':''}><input type="checkbox" checked={selected.includes(s.studentCode)} disabled={disabled} onChange={()=>toggle(s.studentCode)}/><span><strong>{s.fullName}</strong><small>{s.studentCode} · {s.teamName||`Nhóm #${s.teamId||s.idTeam}`}{enrolled.has(s.studentCode)?' · Đã ghi danh trong đợt này':''}</small></span></label>}):<span className="student-list-empty">{periodId?'Không có sinh viên thuộc đợt bảo vệ đã chọn.':'Không có sinh viên đã xếp nhóm phù hợp.'}</span>}</div></div>}
function EnrollmentDetail({item}){return <><div className="enrollment-detail"><Detail label="Mã sinh viên" value={item.studentCode}/><Detail label="Lớp" value={item.classCode}/><Detail label="Nhóm" value={item.teamName}/><Detail label="Đợt bảo vệ" value={`${item.defensePeriodName} · ${item.academicYear}`}/><Detail label="Trạng thái" value={STATUS[item.status]}/><Detail label="Ngày ghi danh" value={formatDate(item.enrolledAt)}/><Detail label="Ngày hoàn tất" value={formatDate(item.completedAt)}/><Detail label="Ghi chú" value={item.note}/></div></>}
function Detail({label,value}){return <div><span>{label}</span><strong>{value||'Chưa cập nhật'}</strong></div>}
function State(){return <div className="enrollment-empty"><LoaderCircle className="spin"/><strong>Đang tải hồ sơ ghi danh...</strong></div>}
function formatDate(v){return formatDateTimeDisplay(v)}
