import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, BookOpen, ChevronLeft, ChevronRight, Edit3, Eye, Inbox, LoaderCircle, Plus, Search, Trash2, X } from 'lucide-react';
import LibraryTopicService from '../../services/LibraryTopicService.js';
import { useToast } from '../../context/ToastContext.jsx';
import getApiErrorMessage from '../../utils/apiError.js';
import ConfirmModal from '../../components/feedback/ConfirmModal.jsx';

const emptyForm = { title: '', description: '', objective: '', technology: '' };

export default function LibraryTopicPage({ canManage = false }) {
  const toast = useToast();
  const [items, setItems] = useState([]); const [page, setPage] = useState(0);
  const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [modal, setModal] = useState(null); const [confirm, setConfirm] = useState(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');

  const load = async () => { setLoading(true); setError(''); try { setItems(await LibraryTopicService.listAll()); } catch (requestError) { setError(requestError.message || 'Không thể tải thư viện đề tài.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { setPage(0); }, [query]);
  const filtered = useMemo(() => { const term = normalizeSearch(query); return items.filter((item) => normalizeSearch(`${item.title} ${item.description || ''} ${item.objective || ''} ${item.technology || ''}`).includes(term)); }, [items, query]);
  const totalPages = Math.ceil(filtered.length / 9); const visibleItems = filtered.slice(page * 9, page * 9 + 9);

  const openCreate = () => { setForm(emptyForm); setFormError(''); setModal({ mode: 'create' }); };
  const openDetail = async (item, mode) => { setFormError(''); setModal({ mode: 'loading', item }); try { const response = await LibraryTopicService.detail(item.idLibraryTopic); const detail = response?.result || item; setForm({ title: detail.title || '', description: detail.description || '', objective: detail.objective || '', technology: detail.technology || '' }); setModal({ mode, item: detail }); } catch (requestError) { setModal(null); setError(requestError.message || 'Không thể tải chi tiết đề tài.'); } };
  const openView = (item) => openDetail(item, 'view');
  const openEdit = (item) => openDetail(item, 'edit');
  const submit = async (event) => { event.preventDefault(); if (!form.title.trim()) { const message = 'Tên đề tài không được để trống.'; setFormError(message); toast.error(message, { title: 'Dữ liệu chưa hợp lệ' }); return; } setSaving(true); setFormError(''); try { const editing = modal.mode === 'edit'; if (editing) await LibraryTopicService.update(modal.item.idLibraryTopic, form); else await LibraryTopicService.create(form); setModal(null); toast.success(editing ? 'Cập nhật đề tài tham khảo thành công.' : 'Thêm đề tài tham khảo thành công.'); await load(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể lưu đề tài tham khảo.'); setFormError(message); toast.error(message, { title: 'Dữ liệu chưa hợp lệ' }); } finally { setSaving(false); } };
  const remove = async (item) => { setSaving(true); try { await LibraryTopicService.remove(item.idLibraryTopic); setConfirm(null); toast.success('Xóa đề tài tham khảo thành công.'); await load(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể xóa đề tài.'); setError(message); toast.error(message); } finally { setSaving(false); } };
  const confirmAction = () => { if (confirm.type === 'edit') { const item = confirm.item; setConfirm(null); openEdit(item); } else remove(confirm.item); };

  return <div className="page-stack library-page">
    <section className="page-title-row"><div><span className="page-kicker">KHO TRI THỨC ĐỒ ÁN</span><h2>Thư viện đề tài tham khảo</h2><p>Tra cứu ý tưởng, mục tiêu và công nghệ từ các đề tài được lưu trong hệ thống.</p></div>{canManage && <button className="primary-button" onClick={openCreate}><Plus size={18} /> Thêm đề tài</button>}</section>
    <section className="library-toolbar panel"><label><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên, mô tả, mục tiêu hoặc công nghệ..." /></label><span>{filtered.length} đề tài phù hợp</span></section>
    {loading ? <State icon={LoaderCircle} text="Đang tải thư viện đề tài..." spin /> : error ? <State icon={AlertCircle} text={error} action={load} /> : filtered.length === 0 ? <State icon={Inbox} text="Chưa có đề tài tham khảo phù hợp." /> : <section className="library-grid">{visibleItems.map((item) => <article className="library-card" key={item.idLibraryTopic}><div className="library-card-icon"><BookOpen size={21} /></div><div className="library-card-body"><span>ĐỀ TÀI #{item.idLibraryTopic}</span><h3>{item.title}</h3><p>{item.description || 'Chưa có mô tả cho đề tài này.'}</p><div className="tech-tags">{splitTech(item.technology).map((tech) => <i key={tech}>{tech}</i>)}</div></div><div className="library-card-actions"><button onClick={() => openView(item)}><Eye size={16} /> Xem chi tiết</button>{canManage && <><button className="icon-action" onClick={() => setConfirm({ type: 'edit', item })} aria-label="Sửa"><Edit3 size={16} /></button><button className="icon-action danger" onClick={() => setConfirm({ type: 'delete', item })} aria-label="Xóa"><Trash2 size={16} /></button></>}</div></article>)}</section>}
    {!loading && !error && totalPages > 1 && <div className="library-pagination"><button disabled={page === 0} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={17} /></button><span>Trang {page + 1}/{totalPages}</span><button disabled={page >= totalPages - 1} onClick={() => setPage((value) => value + 1)}><ChevronRight size={17} /></button></div>}
    {modal && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setModal(null)}><section className="topic-modal" role="dialog" aria-modal="true"><header><div><span>{modal.mode === 'create' ? 'THÊM MỚI' : modal.mode === 'edit' ? 'CHỈNH SỬA' : 'CHI TIẾT'}</span><h3>Đề tài tham khảo</h3></div><button onClick={() => setModal(null)}><X size={20} /></button></header>{modal.mode === 'loading' ? <div className="data-state"><LoaderCircle className="spin" size={28} /><strong>Đang tải chi tiết...</strong></div> : <form onSubmit={submit}><label>Tên đề tài <b>*</b><input disabled={modal.mode === 'view'} value={form.title || ''} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Nhập tên đề tài" /></label><label>Mô tả<textarea disabled={modal.mode === 'view'} value={form.description || ''} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Mô tả bài toán và phạm vi" /></label><label>Mục tiêu<textarea disabled={modal.mode === 'view'} value={form.objective || ''} onChange={(e) => setForm({ ...form, objective: e.target.value })} placeholder="Mục tiêu cần đạt được" /></label><label>Công nghệ<textarea disabled={modal.mode === 'view'} value={form.technology || ''} onChange={(e) => setForm({ ...form, technology: e.target.value })} placeholder="Ví dụ: React, Spring Boot, MySQL" /></label>{formError && <div className="form-error"><AlertCircle size={16} />{formError}</div>}<footer><button type="button" className="secondary-button" onClick={() => setModal(null)}>{modal.mode === 'view' ? 'Đóng' : 'Hủy'}</button>{modal.mode !== 'view' && <button className="primary-button" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu đề tài'}</button>}</footer></form>}</section></div>}
    <ConfirmModal open={Boolean(confirm)} type={confirm?.type} title={confirm?.type === 'delete' ? 'Xóa đề tài tham khảo?' : 'Chỉnh sửa đề tài?'} message={confirm?.type === 'delete' ? `Đề tài “${confirm?.item?.title || ''}” sẽ bị xóa khỏi thư viện.` : `Bạn sắp thay đổi nội dung đề tài “${confirm?.item?.title || ''}”.`} confirmLabel={confirm?.type === 'delete' ? 'Xóa đề tài' : 'Tiếp tục sửa'} loading={saving} onCancel={() => setConfirm(null)} onConfirm={confirmAction} />
  </div>;
}

function State({ icon: Icon, text, action, spin }) { return <section className="panel data-state"><Icon className={spin ? 'spin' : ''} size={29} /><strong>{text}</strong>{action && <button onClick={action}>Thử lại</button>}</section>; }
function splitTech(value) { return value ? value.split(/[,;/]/).map((item) => item.trim()).filter(Boolean).slice(0, 4) : ['Chưa cập nhật công nghệ']; }
function normalizeSearch(value) { return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('vi').trim(); }
