import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, CalendarClock, CheckCircle2, Edit3, LoaderCircle, Plus, Search, Trash2, X, XCircle } from 'lucide-react';
import API_ENDPOINTS from '../../config/endpoints.js';
import ResourceService from '../../services/ResourceService.jsx';
import { useToast } from '../../context/ToastContext.jsx';
import getApiErrorMessage from '../../utils/apiError.js';
import { formatDateTimeDisplay } from '../../utils/dateFormat.js';
import ConfirmModal from '../../components/feedback/ConfirmModal.jsx';
import '../../style/WorkflowPages.scss';

const TYPES = [
  ['TOPIC_REGISTRATION_FORM', 'Phiếu đăng ký đề tài'], ['ASSIGNMENT_FORM', 'Phiếu giao đề tài'],
  ['PROJECT_DIARY', 'Nhật ký đồ án'], ['PROGRESS_REPORT', 'Báo cáo tiến độ'],
  ['FINAL_REPORT', 'Báo cáo cuối kỳ'], ['DEFENSE_SLIDE', 'Slide bảo vệ'],
  ['SOURCE_CODE', 'Mã nguồn'], ['OTHER', 'Khác'],
];
const STATUS = { DRAFT: 'Bản nháp', OPEN: 'Đang mở', CLOSED: 'Đã đóng', CANCELLED: 'Đã hủy' };
const emptyForm = { defensePeriodId: '', milestoneName: '', description: '', startAt: '', deadline: '', milestoneType: 'PROGRESS_REPORT', allowLateSubmission: true, required: true, maxFileSizeMb: 20, allowedFileTypes: 'pdf,doc,docx,zip' };

export default function MilestonePage() {
  const toast = useToast();
  const [items, setItems] = useState([]); const [periods, setPeriods] = useState([]); const [query, setQuery] = useState('');
  const [status, setStatus] = useState(''); const [periodId, setPeriodId] = useState(''); const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null); const [confirm, setConfirm] = useState(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const [milestones, defensePeriods] = await Promise.all([ResourceService.getAll(API_ENDPOINTS.milestones.list, { ...(periodId && { defensePeriodId: periodId }), ...(status && { status }), ...(query.trim() && { keyword: query.trim() }) }), ResourceService.getAll(API_ENDPOINTS.defensePeriods.list)]); setItems(milestones); setPeriods(defensePeriods); } catch (e) { toast.error(getApiErrorMessage(e, 'Không thể tải danh sách mốc tiến độ.')); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [query, status, periodId]); // eslint-disable-line react-hooks/exhaustive-deps
  const activePeriods = useMemo(() => periods.filter((p) => p.status !== 'FINISHED'), [periods]);
  const selectedPeriod = useMemo(() => periods.find((p) => String(p.defensePeriodId) === String(form.defensePeriodId)), [periods, form.defensePeriodId]);
  const periodMin = selectedPeriod?.startDate ? `${selectedPeriod.startDate}T00:00` : undefined;
  const periodMax = selectedPeriod?.endDate ? `${selectedPeriod.endDate}T23:59` : undefined;
  const openCreate = () => { const first = activePeriods[0]; setForm({ ...emptyForm, defensePeriodId: first?.defensePeriodId || '', startAt: first?.startDate ? `${first.startDate}T08:00` : '', deadline: first?.endDate ? `${first.endDate}T23:59` : '' }); setError(''); setModal({ mode: 'create' }); };
  const openEdit = (row) => { setForm({ defensePeriodId: row.defensePeriodId, milestoneName: row.milestoneName || '', description: row.description || '', startAt: inputDate(row.startAt), deadline: inputDate(row.deadline), milestoneType: row.milestoneType, allowLateSubmission: row.allowLateSubmission, required: row.required, maxFileSizeMb: row.maxFileSize ? row.maxFileSize / 1048576 : '', allowedFileTypes: (row.allowedFileTypes || []).join(',') }); setError(''); setModal({ mode: 'edit', row }); };
  const save = async (event) => { event.preventDefault(); setError(''); if (periodMin && periodMax && (form.startAt < periodMin || form.deadline > periodMax)) { setError(`Thời gian mốc tiến độ phải nằm trong đợt bảo vệ, từ ${formatDate(periodMin)} đến ${formatDate(periodMax)}.`); return; } if (form.startAt >= form.deadline) { setError('Thời gian bắt đầu phải trước hạn nộp.'); return; } setSaving(true); const payload = { milestoneName: form.milestoneName.trim(), description: form.description.trim() || null, startAt: form.startAt, deadline: form.deadline, milestoneType: form.milestoneType, allowLateSubmission: form.allowLateSubmission, required: form.required, maxFileSize: form.maxFileSizeMb ? Math.round(Number(form.maxFileSizeMb) * 1048576) : null, allowedFileTypes: form.allowedFileTypes.trim() || null }; try { if (modal.mode === 'create') await ResourceService.create(API_ENDPOINTS.milestones.create(form.defensePeriodId), payload); else await ResourceService.update(API_ENDPOINTS.milestones.update(modal.row.milestoneId), payload); toast.success(modal.mode === 'create' ? 'Đã tạo mốc tiến độ.' : 'Đã cập nhật mốc tiến độ.'); setModal(null); await load(); } catch (e) { setError(getApiErrorMessage(e, 'Không thể lưu mốc tiến độ.')); } finally { setSaving(false); } };
  const action = (row, kind) => setConfirm({ row, kind });
  const executeAction = async () => { const { row, kind } = confirm; const labels = { open: 'mở', close: 'đóng', cancel: 'hủy', remove: 'xóa' }; setSaving(true); try { if (kind === 'remove') await ResourceService.remove(API_ENDPOINTS.milestones.remove(row.milestoneId)); else await ResourceService.update(API_ENDPOINTS.milestones[kind](row.milestoneId), null, 'patch'); toast.success(`Đã ${labels[kind]} mốc tiến độ.`); setConfirm(null); await load(); } catch (e) { toast.error(getApiErrorMessage(e, `Không thể ${labels[kind]} mốc tiến độ.`)); } finally { setSaving(false); } };
  return <div className="workflow-page"><div className="page-heading"><div><span>QUẢN LÝ TIẾN ĐỘ</span><h1>Mốc tiến độ đồ án</h1><p>Thiết lập thời gian, yêu cầu tệp và trạng thái nhận bài cho từng đợt bảo vệ.</p></div><button className="primary-button" onClick={openCreate}><Plus size={17}/> Tạo mốc tiến độ</button></div>
    <ConfirmModal open={Boolean(confirm)} type={confirm?.kind === 'remove' ? 'delete' : 'warning'} title={confirmTitle(confirm?.kind)} message={confirm ? confirmMessage(confirm.kind, confirm.row.milestoneName) : ''} confirmLabel={confirmLabel(confirm?.kind)} loading={saving} onCancel={() => setConfirm(null)} onConfirm={executeAction}/>
    <section className="workflow-panel"><div className="workflow-toolbar"><label><Search size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên hoặc mô tả..."/></label><select value={periodId} onChange={(e) => setPeriodId(e.target.value)}><option value="">Tất cả đợt bảo vệ</option>{periods.map((p) => <option key={p.defensePeriodId} value={p.defensePeriodId}>{p.periodName} · {p.academicYear}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(STATUS).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></div>
      {loading ? <State icon={LoaderCircle} text="Đang tải mốc tiến độ..." spin/> : items.length === 0 ? <State icon={CalendarClock} text="Chưa có mốc tiến độ phù hợp."/> : <div className="workflow-table"><table><thead><tr><th>Mốc tiến độ</th><th>Đợt bảo vệ</th><th>Thời gian</th><th>Yêu cầu</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map((row) => <tr key={row.milestoneId}><td><strong>{row.milestoneName}</strong><small>{typeLabel(row.milestoneType)} · {row.submissionCount || 0} bài nộp</small></td><td>{row.defensePeriodName}<small>{row.academicYear}</small></td><td>{formatDate(row.startAt)}<small>Hạn: {formatDate(row.deadline)}</small></td><td>{row.required ? 'Bắt buộc' : 'Tùy chọn'}<small>{row.allowLateSubmission ? 'Cho phép nộp muộn' : 'Không nộp muộn'}</small></td><td><span className={`workflow-status ${row.status.toLowerCase()}`}>{STATUS[row.status]}</span></td><td><div className="workflow-actions">{row.status === 'DRAFT' && <><button title="Chỉnh sửa" onClick={() => openEdit(row)}><Edit3 size={15}/></button><button title="Mở nhận bài" onClick={() => action(row,'open')}><CheckCircle2 size={15}/></button><button className="danger" title="Xóa" onClick={() => action(row,'remove')}><Trash2 size={15}/></button></>}{row.status === 'OPEN' && <><button title="Đóng nhận bài" onClick={() => action(row,'close')}><XCircle size={15}/></button><button className="danger" title="Hủy" onClick={() => action(row,'cancel')}><X size={15}/></button></>}</div></td></tr>)}</tbody></table></div>}
    </section>{modal && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && !saving && setModal(null)}><section className="workflow-modal"><header><div><span>{modal.mode === 'create' ? 'THÊM MỚI' : 'CẬP NHẬT'}</span><h3>Mốc tiến độ</h3></div><button onClick={() => setModal(null)}><X size={19}/></button></header><form onSubmit={save}><div className="workflow-form-grid">{modal.mode === 'create' && <label>Đợt bảo vệ<b>*</b><select required value={form.defensePeriodId} onChange={(e) => setForm({...form,defensePeriodId:e.target.value})}><option value="">Chọn đợt bảo vệ</option>{activePeriods.map((p) => <option key={p.defensePeriodId} value={p.defensePeriodId}>{p.periodName} · {p.academicYear}</option>)}</select></label>}<Field label="Tên mốc" required value={form.milestoneName} onChange={(v)=>setForm({...form,milestoneName:v})}/><label>Loại mốc<b>*</b><select value={form.milestoneType} onChange={(e)=>setForm({...form,milestoneType:e.target.value})}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><DateTimeField label="Bắt đầu" required value={form.startAt} onChange={(v)=>setForm({...form,startAt:v})}/><DateTimeField label="Hạn nộp" required value={form.deadline} onChange={(v)=>setForm({...form,deadline:v})}/><Field label="Dung lượng tối đa (MB)" type="number" value={form.maxFileSizeMb} onChange={(v)=>setForm({...form,maxFileSizeMb:v})}/><Field label="Định dạng cho phép" value={form.allowedFileTypes} disabled onChange={(v)=>setForm({...form,allowedFileTypes:v})}/><label className="wide">Mô tả<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.required} onChange={(e)=>setForm({...form,required:e.target.checked})}/> Bắt buộc nộp</label><label className="check"><input type="checkbox" checked={form.allowLateSubmission} onChange={(e)=>setForm({...form,allowLateSubmission:e.target.checked})}/> Cho phép nộp muộn</label></div>{error && <div className="workflow-error"><AlertCircle size={16}/>{error}</div>}<footer><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Hủy</button><button className="primary-button" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu dữ liệu'}</button></footer></form></section></div>}</div>;
}
function Field({label,required,type='text',value,onChange,disabled=false}) { return <label>{label}{required&&<b>*</b>}<input required={required} disabled={disabled} type={type} min={type==='number'?'1':undefined} step={type==='number'?'1':undefined} value={value} onChange={(e)=>onChange(e.target.value)}/></label>; }
function DateTimeField({label,required,value,onChange}) { const pickerRef = useRef(null); const openPicker = () => { const picker = pickerRef.current; if (!picker) return; try { if (typeof picker.showPicker === 'function') picker.showPicker(); else picker.focus(); } catch { picker.focus(); } }; return <label className="datetime-field">{label}{required&&<b>*</b>}<div className="datetime-control"><input type="text" readOnly required={required} value={formatDateTimeInput(value)} placeholder="dd/mm/yyyy HH:mm" onClick={openPicker} onKeyDown={(e)=>{if(e.key==='Enter'||e.key===' ') { e.preventDefault(); openPicker(); }}} aria-label={`${label}, định dạng ngày giờ dd/mm/yyyy HH:mm`}/><button type="button" className="datetime-picker-button" onClick={openPicker} aria-label={`Chọn ${label.toLowerCase()}`}><CalendarClock size={15}/></button><input ref={pickerRef} className="datetime-native-picker" type="datetime-local" lang="vi-VN" required={required} value={value||''} onChange={(e)=>onChange(e.target.value)}/></div></label>; }
function State({icon:Icon,text,spin}) { return <div className="workflow-state"><Icon className={spin?'spin':''}/><strong>{text}</strong></div>; }
function confirmTitle(kind) { return { open: 'Mở nhận bài?', close: 'Đóng nhận bài?', cancel: 'Hủy mốc tiến độ?', remove: 'Xóa mốc tiến độ?' }[kind] || 'Xác nhận thao tác'; }
function confirmLabel(kind) { return { open: 'Mở nhận bài', close: 'Đóng nhận bài', cancel: 'Hủy mốc', remove: 'Xóa mốc' }[kind] || 'Xác nhận'; }
function confirmMessage(kind, name) { const action = { open: 'mở nhận bài cho', close: 'đóng nhận bài của', cancel: 'hủy', remove: 'xóa' }[kind]; return `Bạn có chắc chắn muốn ${action} mốc “${name}”?`; }
function inputDate(v){return v?String(v).slice(0,16):'';} function formatDateTimeInput(v){const match=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/);return match?`${match[3]}/${match[2]}/${match[1]} ${match[4]}:${match[5]}`:'';} function formatDate(v){return formatDateTimeDisplay(v)} function typeLabel(v){return TYPES.find(([x])=>x===v)?.[1]||v;}
