import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, BookOpen, Check, ChevronDown, Copy, Download, Edit3, Eye, Inbox, KeyRound, LoaderCircle, Plus, Search, Trash2, Upload, UserPlus, Users, X } from 'lucide-react';
import useResourcePage from '../../hooks/useResourcePage.jsx';
import ResourceService from '../../services/ResourceService.jsx';
import { useToast } from '../../context/ToastContext.jsx';
import getApiErrorMessage from '../../utils/apiError.js';
import ConfirmModal from '../../components/feedback/ConfirmModal.jsx';
import '../../style/Search.scss';

const defaultColumns = [{ key: 'id', label: 'Mã' }, { key: 'name', label: 'Thông tin' }, { key: 'owner', label: 'Người phụ trách' }, { key: 'updatedAt', label: 'Ngày cập nhật', format: 'date' }, { key: 'status', label: 'Trạng thái', format: 'status' }];

export default function ModulePage({ title, description, actionLabel = 'Thêm mới', endpoint, columns = defaultColumns, emptyMessage = 'Chưa có dữ liệu để hiển thị.', crud, importEndpoint, exportEndpoint, exportYearsEndpoint, exportEntityLabel = 'sinh viên', readOnly = false, searchFields, serverSearch = false, searchPlaceholder = 'Tìm kiếm...' }) {
  const toast = useToast();
  const [input, setInput] = useState(''); const [modal, setModal] = useState(null); const [memberModal, setMemberModal] = useState(null); const [selectedStudentCodes, setSelectedStudentCodes] = useState([]); const [memberQuery, setMemberQuery] = useState(''); const [detail, setDetail] = useState(null); const [detailLoading, setDetailLoading] = useState(false); const [confirm, setConfirm] = useState(null); const [statusReason, setStatusReason] = useState(''); const [pendingImport, setPendingImport] = useState(null); const [importFileError, setImportFileError] = useState(''); const [openingFilePicker, setOpeningFilePicker] = useState(false); const [form, setForm] = useState({}); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState(''); const [resetResult, setResetResult] = useState(null); const [copied, setCopied] = useState(false); const [exportModal, setExportModal] = useState(false); const [academicYears, setAcademicYears] = useState([]); const [exportYearId, setExportYearId] = useState(''); const fileRef = useRef(null); const pickerTimerRef = useRef(null);
  const activeSearchFields = useMemo(() => searchFields || columns.map((column) => column.key), [searchFields, columns]);
  const { content, page, setPage, totalElements, totalPages, first, last, keyword, setKeyword, loading, error, reload } = useResourcePage(endpoint, { searchFields: activeSearchFields, serverSearch });
  const canCreate = !readOnly && Boolean(crud?.create && crud?.fields?.length); const canEdit = !readOnly && Boolean(crud?.update && crud?.fields?.length); const canDelete = !readOnly && Boolean(crud?.remove);
  const submitSearch = (event) => { event.preventDefault(); setPage(0); setKeyword(input.trim()); };
  useEffect(() => { const timer = window.setTimeout(() => { setPage(0); setKeyword(input.trim()); }, 300); return () => window.clearTimeout(timer); }, [input, setKeyword, setPage]);
  useEffect(() => { setActionError(''); setModal(null); setConfirm(null); setDetail(null); }, [endpoint, title]);
  useEffect(() => { if (!actionError) return undefined; const timer = window.setTimeout(() => setActionError(''), 5000); return () => window.clearTimeout(timer); }, [actionError]);
  useEffect(() => { const finishOpening = () => setOpeningFilePicker(false); window.addEventListener('focus', finishOpening); return () => { window.removeEventListener('focus', finishOpening); if (pickerTimerRef.current) window.clearTimeout(pickerTimerRef.current); }; }, []);
  const openCreate = () => { setActionError(''); setForm(Object.fromEntries((crud.fields || []).map((field) => [field.name, field.defaultValue ?? (field.type === 'checkbox' ? false : '')]))); setModal({ mode: 'create' }); };
  const openEdit = (row) => { setActionError(''); const fields = crud.fields.filter((field) => !field.createOnly); setForm(Object.fromEntries(fields.map((field) => [field.name, toInputValue(valueAt(row, field.source || field.name), field.type)]))); setModal({ mode: 'edit', row }); };
  const openDetail = async (row) => { setDetail({ ...row, loading: true }); setDetailLoading(true); try { const result = await ResourceService.getOne(crud.detail(getId(row, crud.idKey))); setDetail(result); } catch (requestError) { setDetail(null); toast.error(getApiErrorMessage(requestError, 'Không thể tải chi tiết nhóm.')); } finally { setDetailLoading(false); } };
  const openAddStudent = async (row) => { setActionError(''); setSelectedStudentCodes([]); setMemberQuery(''); setSaving(true); try { const [team, students] = await Promise.all([ResourceService.getOne(crud.detail(getId(row, crud.idKey))), ResourceService.getAll(crud.studentsEndpoint)]); const memberCodes = new Set((team?.students || []).map((student) => String(student.studentCode))); const availableStudents = students.filter((student) => !memberCodes.has(String(student.studentCode)) && !student.teamId && !student.idTeam); setMemberModal({ row, availableStudents }); } catch (requestError) { toast.error(getApiErrorMessage(requestError, 'Không thể tải danh sách sinh viên.')); } finally { setSaving(false); } };
  const toggleStudent = (studentCode) => { const code = String(studentCode); setSelectedStudentCodes((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]); };
  const submitAddStudent = async (event) => { event.preventDefault(); if (selectedStudentCodes.length === 0) { setActionError('Vui lòng chọn ít nhất một sinh viên cần thêm vào nhóm.'); return; } setSaving(true); setActionError(''); try { await ResourceService.create(crud.addStudents(getId(memberModal.row, crud.idKey)), selectedStudentCodes); const count = selectedStudentCodes.length; setMemberModal(null); setSelectedStudentCodes([]); toast.success(`Đã thêm ${count} sinh viên vào nhóm.`); await reload(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể thêm sinh viên vào nhóm.'); setActionError(message); toast.error(message, { title: 'Thêm sinh viên thất bại' }); } finally { setSaving(false); } };
  const submit = async (event) => { event.preventDefault(); const activeFields = crud.fields.filter((field) => modal.mode === 'create' || !field.createOnly); const missing = activeFields.find((field) => field.required && (form[field.name] === '' || form[field.name] === null || form[field.name] === undefined)); if (missing) { const message = `${missing.label} không được để trống.`; setActionError(message); toast.error(message, { title: 'Dữ liệu chưa hợp lệ' }); return; } setSaving(true); setActionError(''); try { const payload = buildPayload(form, activeFields); if (modal.mode === 'create') await ResourceService.create(crud.create, payload); else await ResourceService.update(crud.update(getId(modal.row, crud.idKey)), payload, crud.updateMethod); const successMessage = modal.mode === 'create' ? 'Thêm dữ liệu thành công.' : 'Cập nhật dữ liệu thành công.'; setModal(null); toast.success(successMessage); await reload(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể lưu dữ liệu.'); setActionError(message); toast.error(message, { title: 'Dữ liệu chưa hợp lệ' }); } finally { setSaving(false); } };
  const executeRemove = async (row) => { setSaving(true); setActionError(''); try { const key = crud.removeKey || crud.idKey; await ResourceService.remove(crud.remove(getId(row, key))); setConfirm(null); toast.success('Xóa dữ liệu thành công.'); await reload(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể xóa dữ liệu.'); setActionError(message); toast.error(message); } finally { setSaving(false); } };
  const executeResetPassword = async (row) => { const userName = row.userName; if (!userName) return; setSaving(true); setActionError(''); try { const response = await ResourceService.update(crud.resetPassword(userName), null, 'patch'); const result = response?.result; setConfirm(null); setCopied(false); setResetResult(result); toast.success('Đặt lại mật khẩu thành công.'); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể đặt lại mật khẩu.'); setActionError(message); toast.error(message, { title: 'Reset mật khẩu thất bại' }); } finally { setSaving(false); } };
  const executeQuickStatus = async (row, nextStatus) => { const action = quickStatusAction(crud.quickStatus, nextStatus); if (action?.requiresReason && !statusReason.trim()) { const message = 'Vui lòng nhập lý do từ chối đề tài.'; setActionError(message); toast.error(message, { title: 'Thiếu lý do từ chối' }); return; } setSaving(true); setActionError(''); try { if (action?.endpoint) await ResourceService.create(action.endpoint(getId(row, crud.idKey)), action.requiresReason ? { reason: statusReason.trim() } : null); else { const payload = buildPayloadFromRow(row, crud.fields, { [crud.quickStatus.field]: nextStatus }); await ResourceService.update(crud.update(getId(row, crud.idKey)), payload, crud.updateMethod); } setConfirm(null); setStatusReason(''); toast.success(`Đã cập nhật trạng thái thành “${quickStatusLabel(crud.quickStatus, nextStatus)}”.`); await reload(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Không thể cập nhật trạng thái.'); setActionError(message); toast.error(message, { title: 'Cập nhật trạng thái thất bại' }); } finally { setSaving(false); } };
  const handleConfirm = () => { if (confirm.type === 'edit') { const row = confirm.row; setConfirm(null); openEdit(row); } else if (confirm.type === 'delete') executeRemove(confirm.row); else if (confirm.type === 'reset') executeResetPassword(confirm.row); else if (confirm.type === 'status') executeQuickStatus(confirm.row, confirm.nextStatus); else if (confirm.type === 'import') executeImport(); };
  const copyPassword = async () => { if (!resetResult?.temporaryPassword) return; try { await navigator.clipboard.writeText(resetResult.temporaryPassword); setCopied(true); toast.success('Đã sao chép mật khẩu tạm.'); } catch { toast.error('Không thể sao chép tự động. Hãy sao chép thủ công.'); } };
  const selectImportFile = (event) => { const file = event.target.files?.[0]; if (!file) return; const isExcel = file.name.toLowerCase().endsWith('.xlsx'); if (!isExcel) { setPendingImport(null); setImportFileError(`File “${file.name}” không phải file Excel hợp lệ. Hệ thống chỉ chấp nhận định dạng .xlsx.`); event.target.value = ''; return; } setActionError(''); setPendingImport(file); setConfirm({ type: 'import' }); };
  const openFilePicker = () => { if (openingFilePicker) return; setOpeningFilePicker(true); window.requestAnimationFrame(() => { window.setTimeout(() => { fileRef.current?.click(); pickerTimerRef.current = window.setTimeout(() => setOpeningFilePicker(false), 1200); }, 80); }); };
  const executeImport = async () => { if (!pendingImport) return; setSaving(true); setActionError(''); try { const response = await ResourceService.importFile(importEndpoint, pendingImport); const result = response?.result; if ((result?.failedRows ?? 0) > 0 || (Array.isArray(result?.errors) && result.errors.length > 0)) { const details = result.errors?.map((item) => item?.message || item).filter(Boolean); const duplicate = details?.some((message) => /tồn tại|đã có|existed|duplicate/i.test(String(message))); throw { code: duplicate ? 1173 : undefined, message: duplicate ? 'Dữ liệu import đã có trong hệ thống.' : details?.join('\n') || 'Dữ liệu trong file Excel không hợp lệ.' }; } toast.success('Import dữ liệu thành công.'); setConfirm(null); setPendingImport(null); await reload(); } catch (requestError) { const message = getApiErrorMessage(requestError, 'Import dữ liệu thất bại.'); setConfirm(null); setPendingImport(null); setActionError(message); toast.error(message, { title: 'Không thể import dữ liệu' }); } finally { setSaving(false); if (fileRef.current) fileRef.current.value = ''; } };
  const cancelConfirm = () => { if (confirm?.type === 'import') { setPendingImport(null); if (fileRef.current) fileRef.current.value = ''; } setStatusReason(''); setConfirm(null); };
  const openExport = async () => { setActionError(''); setSaving(true); try { const years = await ResourceService.getAll(exportYearsEndpoint); setAcademicYears(years); setExportYearId(years[0] ? String(years[0]) : ''); setExportModal(true); } catch (requestError) { toast.error(getApiErrorMessage(requestError, 'Không thể tải danh sách năm.')); } finally { setSaving(false); } };
  const executeExport = async () => { if (!exportYearId) { toast.error('Vui lòng chọn năm cần xuất.'); return; } setSaving(true); try { const blob = await ResourceService.downloadFile(exportEndpoint, { year: exportYearId }); const url = window.URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `danh-sach-${exportEntityLabel.replaceAll(' ', '-')}-do-an-${exportYearId}.xlsx`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.URL.revokeObjectURL(url); setExportModal(false); toast.success(`Xuất danh sách ${exportEntityLabel} thành công.`); } catch (requestError) { toast.error(getApiErrorMessage(requestError, 'Không thể xuất file Excel.')); } finally { setSaving(false); } };

  const filteredMemberStudents = (memberModal?.availableStudents || []).filter((student) => normalizeText(`${student.fullName || ''} ${student.studentCode || ''}`).includes(normalizeText(memberQuery)));

  return <div className="page-stack">
    <section className="page-title-row"><div><span className="page-kicker">QUẢN LÝ DỮ LIỆU</span><h2>{title}</h2><p>{description}</p></div>{canCreate && <button className="primary-button" onClick={openCreate}><Plus size={18} /> {actionLabel}</button>}</section>
    {actionError && <div className="page-alert"><AlertCircle size={17} />{actionError}<button onClick={() => setActionError('')}><X size={15} /></button></div>}
    <section className="panel data-panel"><div className="table-toolbar"><form className="table-search" onSubmit={submitSearch}><Search size={18} /><input value={input} onChange={(e) => setInput(e.target.value)} placeholder={searchPlaceholder} aria-label={`Tìm kiếm ${title.toLowerCase()}`} />{input && <button type="button" className="search-clear" aria-label="Xóa từ khóa" onClick={() => setInput('')}><X size={15} /></button>}</form><div>{exportEndpoint && <button className="secondary-button" disabled={saving} onClick={openExport}><Download size={17} /> Xuất Excel</button>}{importEndpoint && !readOnly && <><input ref={fileRef} type="file" accept=".xlsx" hidden onChange={selectImportFile} /><button className="secondary-button" disabled={openingFilePicker} onClick={openFilePicker}>{openingFilePicker ? <LoaderCircle className="spin" size={17} /> : <Upload size={17} />} {openingFilePicker ? 'Đang mở...' : 'Import'}</button></>}</div></div>
      {loading ? <DataState icon={LoaderCircle} text="Đang tải dữ liệu từ hệ thống..." spinning /> : error ? <DataState icon={AlertCircle} text={error.message || 'Không thể tải dữ liệu.'} action={reload} /> : content.length === 0 ? <DataState icon={Inbox} text={keyword ? `Không tìm thấy kết quả cho “${keyword}”.` : emptyMessage} /> : <><div className="table-scroll"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}{(crud?.detail || crud?.addStudent || crud?.quickStatus || canEdit || canDelete || crud?.resetPassword) && <th />}</tr></thead><tbody>{content.map((row, index) => <tr key={getRowKey(row, index)}>{columns.map((column) => <td key={column.key} data-label={column.label}>{renderCell(row, column)}</td>)}{(crud?.detail || crud?.addStudent || crud?.quickStatus || canEdit || canDelete || crud?.resetPassword) && <td className="table-actions" data-label="Thao tác"><div className="inline-actions">{crud?.quickStatus && quickStatusOptions(crud.quickStatus, row).length > 0 && <select className="quick-status-select" value="" disabled={saving} aria-label={`Đổi trạng thái ${getDisplayName(row)}`} onChange={(event) => { const nextStatus = event.target.value; if (nextStatus && nextStatus !== row[crud.quickStatus.field]) { setStatusReason(''); setConfirm({ type: 'status', row, nextStatus }); } }}><option value="">Đổi trạng thái</option>{quickStatusOptions(crud.quickStatus, row).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>}{crud?.addStudent && <button className="add-member" disabled={saving} onClick={() => openAddStudent(row)} title="Thêm sinh viên vào nhóm" aria-label={`Thêm sinh viên vào ${getDisplayName(row)}`}><UserPlus size={15} /></button>}{crud?.detail && <button className="view" onClick={() => openDetail(row)} title="Xem chi tiết" aria-label={`Xem chi tiết ${getDisplayName(row)}`}><Eye size={15} /></button>}{crud?.resetPassword && <button className="reset" onClick={() => setConfirm({ type: 'reset', row })} title="Đặt lại mật khẩu"><KeyRound size={15} /></button>}{canEdit && <button onClick={() => setConfirm({ type: 'edit', row })} title="Chỉnh sửa"><Edit3 size={15} /></button>}{canDelete && <button className="danger" onClick={() => setConfirm({ type: 'delete', row })} title="Xóa"><Trash2 size={15} /></button>}</div></td>}</tr>)}</tbody></table></div><div className="table-footer"><span>Hiển thị {content.length} trong tổng số {totalElements} kết quả</span><div><button disabled={first} onClick={() => setPage(Math.max(0, page - 1))}>Trước</button><button className="active">{page + 1}</button><button disabled={last} onClick={() => setPage(Math.min(totalPages - 1, page + 1))}>Sau</button></div></div></>}
    </section>
    {modal && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && setModal(null)}><section className="topic-modal resource-modal" role="dialog" aria-modal="true"><header><div><span>{modal.mode === 'create' ? 'THÊM MỚI' : 'CHỈNH SỬA'}</span><h3>{title}</h3></div><button onClick={() => setModal(null)}><X size={20} /></button></header><form onSubmit={submit} noValidate>{crud.fields.filter((field) => modal.mode === 'create' || !field.createOnly).map((field) => <ResourceField key={field.name} field={field} value={form[field.name]} onChange={(value) => setForm({ ...form, [field.name]: value })} />)}{actionError && <div className="form-error"><AlertCircle size={16} />{actionError}</div>}<footer><button type="button" className="secondary-button" onClick={() => setModal(null)}>Hủy</button><button className="primary-button" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu dữ liệu'}</button></footer></form></section></div>}
    {memberModal && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !saving && setMemberModal(null)}><section className="topic-modal member-modal" role="dialog" aria-modal="true"><header><div><span>THÊM THÀNH VIÊN</span><h3>{getDisplayName(memberModal.row)}</h3></div><button disabled={saving} onClick={() => setMemberModal(null)}><X size={20} /></button></header><form onSubmit={submitAddStudent} noValidate><div className="member-search"><Search size={17} /><input autoFocus value={memberQuery} onChange={(event) => setMemberQuery(event.target.value)} placeholder="Tìm theo tên hoặc mã sinh viên..." /></div><div className="member-select-summary"><span>Danh sách sinh viên</span><strong>Đã chọn {selectedStudentCodes.length}</strong></div><div className="member-select-list">{filteredMemberStudents.length ? filteredMemberStudents.map((student) => { const code = String(student.studentCode); const checked = selectedStudentCodes.includes(code); return <label className={checked ? 'selected' : ''} key={code}><input type="checkbox" checked={checked} onChange={() => toggleStudent(code)} /><span><strong>{student.fullName || 'Chưa cập nhật họ tên'}</strong><small>{code}{student.classCode ? ` · ${student.classCode}` : ''}</small></span><Check size={17} /></label>; }) : <div className="member-list-empty"><Users size={22} /><span>{memberQuery ? 'Không tìm thấy sinh viên phù hợp.' : 'Không còn sinh viên có thể thêm vào nhóm.'}</span></div>}</div>{actionError && <div className="form-error"><AlertCircle size={16} />{actionError}</div>}<footer><button type="button" className="secondary-button" disabled={saving} onClick={() => setMemberModal(null)}>Hủy</button><button className="primary-button" disabled={saving || selectedStudentCodes.length === 0}>{saving ? 'Đang thêm...' : `Thêm ${selectedStudentCodes.length || ''} sinh viên`}</button></footer></form></section></div>}
    {detail && crud?.detailView === 'team' && <TeamDetailModal detail={detail} loading={detailLoading} onClose={() => !detailLoading && setDetail(null)} />}
    {confirm?.type === 'status' && quickStatusAction(crud?.quickStatus, confirm.nextStatus)?.requiresReason ? <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && cancelConfirm()}><section className="topic-modal status-reason-modal" role="dialog" aria-modal="true"><header><div><span>CẬP NHẬT TRẠNG THÁI</span><h3>Từ chối đề tài</h3></div><button onClick={cancelConfirm}><X size={20} /></button></header><div className="status-reason-body"><p>Nhập lý do từ chối đề tài “{getDisplayName(confirm.row)}”.</p><label>Lý do từ chối <b>*</b><textarea autoFocus value={statusReason} onChange={(event) => setStatusReason(event.target.value)} placeholder="Nêu rõ lý do để giảng viên hoặc sinh viên chỉnh sửa..." /></label>{actionError && <div className="form-error"><AlertCircle size={16} />{actionError}</div>}<footer><button className="secondary-button" onClick={cancelConfirm}>Hủy</button><button className="primary-button" disabled={saving || !statusReason.trim()} onClick={handleConfirm}>{saving ? 'Đang cập nhật...' : 'Xác nhận từ chối'}</button></footer></div></section></div> : <ConfirmModal open={Boolean(confirm)} type={confirm?.type} title={confirm?.type === 'import' ? 'Xác nhận import dữ liệu?' : confirm?.type === 'reset' ? 'Đặt lại mật khẩu?' : confirm?.type === 'delete' ? 'Xóa dữ liệu?' : confirm?.type === 'status' ? 'Cập nhật trạng thái?' : 'Chỉnh sửa thông tin?'} message={confirm?.type === 'import' ? `Bạn có muốn gửi file “${pendingImport?.name || ''}” (${formatFileSize(pendingImport?.size)}) lên hệ thống không? Dữ liệu chỉ được import sau khi bạn xác nhận.` : confirm?.type === 'reset' ? `Hệ thống sẽ tạo mật khẩu tạm mới cho tài khoản “${confirm?.row?.userName}”.` : confirm?.type === 'delete' ? `Dữ liệu “${confirm ? getDisplayName(confirm.row) : ''}” sẽ bị xóa hoặc ngừng hoạt động.` : confirm?.type === 'status' ? `Chuyển trạng thái “${confirm ? getDisplayName(confirm.row) : ''}” sang “${quickStatusLabel(crud?.quickStatus, confirm?.nextStatus)}”?` : `Bạn sắp chỉnh sửa thông tin “${confirm ? getDisplayName(confirm.row) : ''}”.`} confirmLabel={confirm?.type === 'import' ? 'Xác nhận import' : confirm?.type === 'reset' ? 'Reset mật khẩu' : confirm?.type === 'delete' ? 'Xóa dữ liệu' : confirm?.type === 'status' ? 'Cập nhật trạng thái' : 'Tiếp tục sửa'} loading={saving} onCancel={cancelConfirm} onConfirm={handleConfirm} />}
    {importFileError && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setImportFileError('')}><section className="confirm-modal delete" role="alertdialog" aria-modal="true"><button className="confirm-close" onClick={() => setImportFileError('')}><X size={19} /></button><div className="confirm-icon"><AlertCircle size={25} /></div><span>FILE KHÔNG HỢP LỆ</span><h3>Không thể import dữ liệu</h3><p>{importFileError}</p><button className="primary-button password-done" onClick={() => setImportFileError('')}>Đóng</button></section></div>}
    {openingFilePicker && <div className="file-picker-loading" role="status" aria-live="polite"><LoaderCircle className="spin" size={22} /><div><strong>Đang mở trình chọn file</strong><span>Vui lòng chờ trong giây lát...</span></div></div>}
    {exportModal && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !saving && setExportModal(false)}><section className="topic-modal resource-modal" role="dialog" aria-modal="true"><header><div><span>XUẤT DỮ LIỆU</span><h3>Danh sách {exportEntityLabel} tham gia đồ án</h3></div><button disabled={saving} onClick={() => setExportModal(false)}><X size={20} /></button></header><div className="export-form"><label htmlFor="export-creation-year">Năm tạo tài khoản {exportEntityLabel}</label><select id="export-creation-year" value={exportYearId} onChange={(event) => setExportYearId(event.target.value)}><option value="">Chọn năm</option>{academicYears.map((year) => <option key={year} value={year}>{year}</option>)}</select>{academicYears.length === 0 && <p className="form-error">Chưa có dữ liệu năm từ trường create_at.</p>}<footer><button className="secondary-button" disabled={saving} onClick={() => setExportModal(false)}>Hủy</button><button className="primary-button" disabled={saving || !exportYearId} onClick={executeExport}>{saving ? 'Đang xuất...' : 'Xuất file Excel'}</button></footer></div></section></div>}
    {resetResult && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && setResetResult(null)}><section className="password-modal" role="dialog" aria-modal="true"><button className="password-close" onClick={() => setResetResult(null)}><X size={19} /></button><div className="password-icon"><KeyRound size={26} /></div><span>RESET MẬT KHẨU THÀNH CÔNG</span><h3>Mật khẩu tạm thời</h3><p>Hãy sao chép và gửi mật khẩu này cho tài khoản <strong>{resetResult.userName}</strong>. Mật khẩu chỉ được hiển thị trong lần này.</p><div className="temporary-password"><code>{resetResult.temporaryPassword}</code><button onClick={copyPassword}>{copied ? <Check size={18} /> : <Copy size={18} />}{copied ? 'Đã sao chép' : 'Sao chép'}</button></div><button className="primary-button password-done" onClick={() => setResetResult(null)}>Đã lưu mật khẩu</button></section></div>}
  </div>;
}

function ResourceField({ field, value, onChange }) { if (field.type === 'searchable-select') return <SearchableSelect field={field} value={value} onChange={onChange} />; if (field.type === 'checkbox') return <label className="checkbox-field"><input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked)} /><span>{field.label}</span></label>; if (field.type === 'textarea') return <label>{field.label}{field.required && <b>*</b>}<textarea required={field.required} value={value ?? ''} onChange={(e) => onChange(e.target.value)} /></label>; if (field.type === 'select') return <label>{field.label}{field.required && <b>*</b>}<select required={field.required} value={value ?? ''} onChange={(e) => onChange(e.target.value)}><option value="">Chọn giá trị</option>{field.options.map((option) => <option key={option.value ?? option} value={option.value ?? option}>{option.label ?? String(option).replaceAll('_', ' ')}</option>)}</select></label>; const handleChange = (event) => { let nextValue = event.target.value; if (field.digitsOnly) nextValue = nextValue.replace(/\D/g, ''); if (field.maxLength) nextValue = nextValue.slice(0, field.maxLength); onChange(nextValue); }; return <label>{field.label}{field.required && <b>*</b>}<input type={field.type || 'text'} required={field.required} value={value ?? ''} inputMode={field.inputMode} maxLength={field.maxLength} onChange={handleChange} /></label>; }
function SearchableSelect({ field, value, onChange }) {
  const [options, setOptions] = useState([]); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [loadingOptions, setLoadingOptions] = useState(true); const [loadError, setLoadError] = useState('');
  const optionEntity = field.optionEntity || 'dữ liệu';
  useEffect(() => { let active = true; ResourceService.getAll(field.endpoint).then((items) => { if (!active) return; const allowedItems = field.optionFilter ? items.filter(field.optionFilter) : items; setOptions(allowedItems); const selected = items.find((item) => String(value) === String(valueAt(item, field.optionValue))); if (selected) setQuery(optionText(selected, field)); }).catch(() => { if (active) setLoadError(`Không thể tải danh sách ${optionEntity}.`); }).finally(() => { if (active) setLoadingOptions(false); }); return () => { active = false; }; }, [field.endpoint, field.optionLabel, field.optionSecondary, field.optionValue, optionEntity]); // eslint-disable-line react-hooks/exhaustive-deps
  const normalizedQuery = normalizeText(query); const filtered = options.filter((item) => normalizeText(optionText(item, field)).includes(normalizedQuery));
  const choose = (item) => { onChange(valueAt(item, field.optionValue)); setQuery(optionText(item, field)); setOpen(false); };
  const changeQuery = (event) => { setQuery(event.target.value); onChange(''); setOpen(true); };
  return <label className="searchable-field">{field.label}{field.required && <b>*</b>}<div className={`searchable-select ${open ? 'open' : ''}`}><Search size={16} /><input value={query} required={field.required} placeholder={loadingOptions ? `Đang tải danh sách ${optionEntity}...` : field.placeholder} onClick={() => setOpen(true)} onFocus={() => setOpen(true)} onChange={changeQuery} autoComplete="off" /><button type="button" className="select-toggle" aria-label={`Hiện danh sách ${optionEntity}`} aria-expanded={open} onClick={() => setOpen((current) => !current)}><ChevronDown size={17} /></button>{open && <div className="searchable-options">{loadError ? <span className="option-message error">{loadError}</span> : loadingOptions ? <span className="option-message">Đang tải danh sách {optionEntity}...</span> : filtered.length ? <><span className="options-caption">Danh sách {optionEntity} · {filtered.length} kết quả</span>{filtered.map((item) => { const optionValue = valueAt(item, field.optionValue); return <button type="button" className={String(value) === String(optionValue) ? 'selected' : ''} key={optionValue} onClick={() => choose(item)}><span><strong>{valueAt(item, field.optionLabel) || valueAt(item, field.optionSecondary)}</strong><small>{valueAt(item, field.optionSecondary)}</small></span>{String(value) === String(optionValue) && <Check size={16} />}</button>; })}</> : <span className="option-message">Không tìm thấy {optionEntity} phù hợp.</span>}</div>}</div></label>;
}
function TeamDetailModal({ detail, loading, onClose }) {
  const students = Array.isArray(detail?.students) ? detail.students : [];
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="team-detail-modal" role="dialog" aria-modal="true" aria-labelledby="team-detail-title"><header><div><span>CHI TIẾT NHÓM SINH VIÊN</span><h3 id="team-detail-title">{detail?.nameTeam || 'Thông tin nhóm'}</h3></div><button disabled={loading} onClick={onClose} aria-label="Đóng"><X size={20} /></button></header>{loading ? <DataState icon={LoaderCircle} text="Đang tải chi tiết nhóm..." spinning /> : <div className="team-detail-body"><div className="team-meta-grid"><div><span>Ngày thành lập</span><strong>{formatDate(detail?.joinDate)}</strong></div><div><span>Vai trò</span><strong>{formatValue(detail?.role)}</strong></div><div className="wide"><span>Mô tả nhóm</span><p>{detail?.description || 'Chưa có mô tả cho nhóm.'}</p></div></div><section className="team-detail-section topic"><div className="section-icon"><BookOpen size={20} /></div><div><span>ĐỀ TÀI CỦA NHÓM</span><h4>{detail?.topicTitle || 'Nhóm chưa lựa chọn đề tài'}</h4><p>{detail?.topicDescription || 'Chưa có mô tả đề tài.'}</p></div></section><section className="team-detail-section"><div className="section-heading"><div><Users size={19} /><div><span>THÀNH VIÊN</span><h4>{students.length} sinh viên trong nhóm</h4></div></div></div>{students.length ? <div className="team-student-list">{students.map((student, index) => <article key={student.studentCode || index}><span className="student-index">{index + 1}</span><div className="student-main"><strong>{student.fullName || 'Chưa cập nhật họ tên'}</strong><span>{student.studentCode || 'Chưa có mã sinh viên'}</span></div><div className="student-extra"><span>{student.classCode || 'Chưa xếp lớp'}</span><small>{student.email || 'Chưa có email'}</small></div></article>)}</div> : <div className="team-empty"><Users size={24} /><span>Nhóm chưa có sinh viên.</span></div>}</section></div>}<footer><button className="primary-button" onClick={onClose} disabled={loading}>Đóng</button></footer></section></div>;
}
function DataState({ icon: Icon, text, action, spinning }) { return <div className="data-state"><Icon className={spinning ? 'spin' : ''} size={28} /><strong>{text}</strong>{action && <button onClick={action}>Thử lại</button>}</div>; }
function getId(row, key) { return valueAt(row, key) ?? row.id; } function getDisplayName(row) { return row.title || row.fullName || row.nameTeam || row.periodName || row.academicYear || row.majorName || row.templateName || 'bản ghi này'; }
function getRowKey(row, index) { return row.id ?? row.userId ?? row.idUser ?? row.topicId ?? row.idTeam ?? row.milestoneId ?? row.assignmentId ?? row.memberId ?? row.submissionId ?? row.scoreId ?? row.templateId ?? row.academicId ?? row.defensePeriodId ?? row.majorId ?? index; }
function valueAt(row, key) { return key?.split('.').reduce((value, part) => value?.[part], row); }
function renderCell(row, column) { const value = valueAt(row, column.key); if (column.render) return column.render(value, row); if (column.format === 'status') return <span className={`status-badge ${statusClass(value)}`}>{formatStatus(value)}</span>; if (column.format === 'date') return formatDate(value); if (column.primary) return <><strong>{formatValue(value)}</strong>{column.secondary && <small>{formatValue(valueAt(row, column.secondary))}</small>}</>; return formatValue(value); }
function buildPayload(form, fields) { return Object.fromEntries(fields.map((field) => { let value = form[field.name]; if (field.type === 'number' && value !== '') value = Number(value); if (field.transform) value = field.transform(value); return [field.name, value === '' && !field.required ? null : value]; })); }
function buildPayloadFromRow(row, fields, overrides = {}) { return Object.fromEntries(fields.filter((field) => !field.createOnly).map((field) => { let value = Object.prototype.hasOwnProperty.call(overrides, field.name) ? overrides[field.name] : valueAt(row, field.source || field.name); if (field.type === 'number' && value !== '' && value != null) value = Number(value); if (field.transform) value = field.transform(value); return [field.name, value === undefined || value === '' && !field.required ? null : value]; })); }
function toInputValue(value, type) { if (value == null) return type === 'checkbox' ? false : ''; if (type === 'datetime-local') return String(value).slice(0, 16); return value; }
function formatValue(value) { if (value === null || value === undefined || value === '') return '—'; if (Array.isArray(value)) return value.length ? value.join(', ') : '—'; return String(value).replaceAll('_', ' '); }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: value.includes?.('T') ? 'short' : undefined }).format(date); }
function statusClass(status = '') { const value = String(status); if (/APPROVED|ACTIVE|COMPLETED|LOCKED/i.test(value)) return 'success'; if (/PENDING|DRAFT|SUBMITTED|IN_PROGRESS|UNDER_REVIEW/i.test(value)) return 'warning'; if (/REJECTED|CANCELLED|INACTIVE|DELETED|LATE/i.test(value)) return 'danger'; return 'info'; }
function formatStatus(value) { const labels = { PENDING: 'Chờ diễn ra', ONGOING: 'Đang diễn ra', FINISHED: 'Đã kết thúc', DRAFT: 'Bản nháp', PENDING_APPROVAL: 'Chờ phê duyệt', APPROVED: 'Đã phê duyệt', REJECTED: 'Đã từ chối', OPEN_FOR_REGISTRATION: 'Mở đăng ký', REGISTERED: 'Đã đăng ký', IN_PROGRESS: 'Đang thực hiện', COMPLETED: 'Đã hoàn thành', CANCELLED: 'Đã hủy' }; return labels[value] || formatValue(value); }
function quickStatusLabel(config, value) { return config?.options?.find((option) => option.value === value)?.label || formatStatus(value); }
function quickStatusAction(config, value) { return config?.options?.find((option) => option.value === value); }
function quickStatusOptions(config, row) { return (config?.options || []).filter((option) => option.value !== row?.[config.field] && (!option.from || option.from.includes(row?.[config.field]))); }
function optionText(item, field) { return [valueAt(item, field.optionLabel), valueAt(item, field.optionSecondary)].filter(Boolean).join(' · '); }
function normalizeText(value) { return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D').toLowerCase().trim(); }
function formatFileSize(size = 0) { if (size < 1024) return `${size} B`; if (size < 1048576) return `${(size / 1024).toFixed(1)} KB`; return `${(size / 1048576).toFixed(1)} MB`; }
