import React, { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AlertCircle, Check, Download, Edit3, Eye, FileText, LoaderCircle, MessageSquare, Search, Send, Trash2, Upload, X } from 'lucide-react';
import API_ENDPOINTS from '../../config/endpoints.js';
import httpClient from '../../config/HttpClient.jsx';
import ResourceService from '../../services/ResourceService.jsx';
import { useToast } from '../../context/ToastContext.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import ConfirmModal from '../../components/feedback/ConfirmModal.jsx';
import getApiErrorMessage from '../../utils/apiError.js';
import { formatDateTimeDisplay } from '../../utils/dateFormat.js';
import '../../style/WorkflowPages.scss';

const STATUS = { SUBMITTED:'Đã nộp', UNDER_REVIEW:'Đang duyệt', REVISION_REQUIRED:'Cần chỉnh sửa', APPROVED:'Đã duyệt', REJECTED:'Từ chối', WITHDRAWN:'Đã thu hồi' };

export default function SubmissionPage({ mode = 'review' }) {
  const student = mode === 'student'; const [searchParams] = useSearchParams(); const scopedTeamId = !student ? searchParams.get('teamId') : null;
  const toast = useToast(); const { user } = useAuth(); const [items,setItems]=useState([]); const [milestones,setMilestones]=useState([]); const [teams,setTeams]=useState([]); const [team,setTeam]=useState(null); const [selectedTeamId,setSelectedTeamId]=useState(''); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [modal,setModal]=useState(null); const [comments,setComments]=useState([]); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [file,setFile]=useState(null); const [note,setNote]=useState(''); const [comment,setComment]=useState(''); const [editingCommentId,setEditingCommentId]=useState(null); const [editingContent,setEditingContent]=useState(''); const [commentConfirm,setCommentConfirm]=useState(null); const [previewOpen,setPreviewOpen]=useState(false); const [previewLoading,setPreviewLoading]=useState(false); const [previewSource,setPreviewSource]=useState(null); const [previewError,setPreviewError]=useState('');
  const load = async () => { setLoading(true); try { if (student) { const myTeams=await ResourceService.getOne(API_ENDPOINTS.teams.mineAll); const availableTeams=Array.isArray(myTeams)?myTeams:[]; const selected=availableTeams.find((item)=>String(item.idTeam)===String(selectedTeamId))||availableTeams[0]; setTeams(availableTeams); setTeam(selected||null); if(selected&&String(selected.idTeam)!==String(selectedTeamId))setSelectedTeamId(String(selected.idTeam)); if(!selected){setMilestones([]);setItems([]);return;} const [ms,subs]=await Promise.all([ResourceService.getAll(API_ENDPOINTS.milestones.list,{defensePeriodId:selected.defensePeriodId}),ResourceService.getAll(API_ENDPOINTS.submissions.byTeam(selected.idTeam),{...(status&&{status})})]); setMilestones(ms); setItems(subs); } else setItems(await ResourceService.getAll(API_ENDPOINTS.submissions.list,{...(status&&{status}), ...(scopedTeamId&&{teamId: scopedTeamId})})); } catch(e){ const message=getApiErrorMessage(e,student?'Bạn chưa thuộc nhóm sinh viên hoặc không thể tải tiến độ.':'Không thể tải danh sách bài nộp.'); setError(message); } finally {setLoading(false);} };
  useEffect(()=>{load();},[status,mode,scopedTeamId,selectedTeamId]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered=useMemo(()=>items.filter((x)=>`${x.fileName} ${x.milestoneName} ${x.teamName} ${x.submittedByName}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const latestByMilestone=useMemo(()=>{const result=new Map();items.filter((item)=>item.status!=='WITHDRAWN').forEach((item)=>{const current=result.get(item.milestoneId);if(!current||item.version>current.version)result.set(item.milestoneId,item);});return result;},[items]);
  useEffect(()=>()=>{if(previewSource)URL.revokeObjectURL(previewSource);},[previewSource]);
  const resetPreview=()=>{setPreviewOpen(false);setPreviewLoading(false);setPreviewSource(null);setPreviewError('');};
  const openDetail=async(row)=>{resetPreview();setSaving(true);setError('');setEditingCommentId(null);setEditingContent('');setComment('');try{const [detail,allComments]=await Promise.all([ResourceService.getOne(API_ENDPOINTS.submissions.detail(row.submissionId)),ResourceService.getAll(API_ENDPOINTS.comments.bySubmission(row.submissionId))]);setComments(allComments);setModal({type:'detail',row:detail});}catch(e){toast.error(getApiErrorMessage(e,'Không thể tải chi tiết bài nộp.'));}finally{setSaving(false);}};
  const closeDetail=()=>{resetPreview();setModal(null);};
  const previewSubmission=async(row)=>{resetPreview();setPreviewOpen(true);const pdf=String(row.contentType||'').toLowerCase().includes('pdf')||String(row.fileName||'').toLowerCase().endsWith('.pdf');if(!pdf){setPreviewError('Trình duyệt chỉ hỗ trợ xem trước trực tiếp tệp PDF. Hãy tải tệp DOC, DOCX hoặc ZIP về máy để xem.');return;}setPreviewLoading(true);try{const data=await httpClient.get(API_ENDPOINTS.submissions.file(row.submissionId),{responseType:'blob'});const blob=data instanceof Blob?data:new Blob([data],{type:'application/pdf'});if(!blob.size)throw new Error('Tệp xem trước không có dữ liệu.');const pdfBlob=blob.type==='application/pdf'?blob:new Blob([blob],{type:'application/pdf'});setPreviewSource(URL.createObjectURL(pdfBlob));}catch(e){setPreviewError(getApiErrorMessage(e,'Không thể tải bản xem trước của bài nộp.'));}finally{setPreviewLoading(false);}};
  const download=async(row)=>{try{const blob=await httpClient.get(API_ENDPOINTS.submissions.file(row.submissionId),{responseType:'blob'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=row.fileName||'submission';anchor.click();URL.revokeObjectURL(url);}catch(e){toast.error(getApiErrorMessage(e,'Không thể tải tệp bài nộp.'));}};
  const chooseFile=(selected)=>{setFile(null);setError('');if(!selected)return;const validationError=validateSubmissionFile(modal.milestone,selected);if(validationError){setError(validationError);return;}setFile(selected);};
  const upload=async(event)=>{event.preventDefault();if(!file){setError('Vui lòng chọn tệp đúng định dạng để nộp.');return;}const validationError=validateSubmissionFile(modal.milestone,file);if(validationError){setError(validationError);return;}setSaving(true);setError('');try{const data=new FormData();data.append('file',file);await httpClient.post(API_ENDPOINTS.submissions.upload(modal.milestone.milestoneId),data,{params:{teamId:team.idTeam,...(note.trim()&&{note:note.trim()})}});toast.success('Nộp bài thành công.');setModal(null);setFile(null);setNote('');await load();}catch(e){setError(getApiErrorMessage(e,'Không thể nộp bài.'));}finally{setSaving(false);}};
  const workflow=async(kind)=>{if(['revise','approve','reject'].includes(kind)&&!comment.trim()){setError('Vui lòng nhập nhận xét trước khi cập nhật trạng thái.');return;}setSaving(true);setError('');try{await ResourceService.update(API_ENDPOINTS.submissions[kind](modal.row.submissionId),['review'].includes(kind)?null:{comment:comment.trim()},'patch');toast.success('Đã cập nhật trạng thái bài nộp.');resetPreview();setModal(null);setComment('');await load();}catch(e){setError(getApiErrorMessage(e,'Không thể cập nhật bài nộp.'));}finally{setSaving(false);}};
  const addComment=async()=>{if(!comment.trim())return;setSaving(true);try{await ResourceService.create(API_ENDPOINTS.comments.create(modal.row.submissionId),{comment:comment.trim()});setComments(await ResourceService.getAll(API_ENDPOINTS.comments.bySubmission(modal.row.submissionId)));setComment('');toast.success('Đã thêm nhận xét.');}catch(e){setError(getApiErrorMessage(e,'Không thể thêm nhận xét.'));}finally{setSaving(false);}};
  const canManageComment=(item)=>{const admin=(user?.roles||[]).some((role)=>String(role).replace(/^ROLE_/,'')==='ADMIN');const owner=(item.authorUserId&&item.authorUserId===user?.userId)||(item.authorUsername&&item.authorUsername===user?.userName);return !student&&item.commentType==='COMMENT'&&(admin||owner);};
  const startEditComment=(item)=>{setEditingCommentId(item.commentId);setEditingContent(item.content);setError('');};
  const updateComment=async(item)=>{if(!editingContent.trim()){setError('Nội dung nhận xét không được để trống.');return;}setSaving(true);setError('');try{await ResourceService.update(API_ENDPOINTS.comments.update(item.commentId),{comment:editingContent.trim()});setComments(await ResourceService.getAll(API_ENDPOINTS.comments.bySubmission(modal.row.submissionId)));setEditingCommentId(null);setEditingContent('');toast.success('Đã cập nhật nhận xét.');}catch(e){setError(getApiErrorMessage(e,'Không thể cập nhật nhận xét.'));}finally{setSaving(false);}};
  const deleteComment=async()=>{if(!commentConfirm)return;setSaving(true);setError('');try{await ResourceService.remove(API_ENDPOINTS.comments.remove(commentConfirm.commentId));setComments(await ResourceService.getAll(API_ENDPOINTS.comments.bySubmission(modal.row.submissionId)));setCommentConfirm(null);toast.success('Đã xóa nhận xét.');}catch(e){setCommentConfirm(null);setError(getApiErrorMessage(e,'Không thể xóa nhận xét.'));}finally{setSaving(false);}};
  const withdraw=async(row)=>{if(!window.confirm(`Thu hồi phiên bản ${row.version} của “${row.fileName}”?`))return;try{await ResourceService.remove(API_ENDPOINTS.submissions.remove(row.submissionId));toast.success('Đã thu hồi bài nộp.');await load();}catch(e){toast.error(getApiErrorMessage(e,'Không thể thu hồi bài nộp.'));}};
  return <div className={`workflow-page ${student ? 'student-submission-page' : 'review-submission-page'}`}><div className="page-heading"><div><span>{student?'TIẾN ĐỘ CỦA NHÓM':'DUYỆT BÀI NỘP'}</span><h1>{student?'Tiến độ và nộp bài':'Bài nộp đồ án'}</h1><p>{student?'Theo dõi deadline, nộp báo cáo và xem phản hồi theo từng phiên bản.':'Tải tệp, nhận xét và xử lý quy trình duyệt báo cáo của các nhóm hướng dẫn.'}</p></div>{student&&team&&<div className="team-chip"><span>NHÓM / ĐỢT BẢO VỆ</span>{teams.length>1?<select value={selectedTeamId} onChange={(e)=>setSelectedTeamId(e.target.value)}>{teams.map((item)=><option key={item.idTeam} value={item.idTeam}>{item.nameTeam} · {item.defensePeriodName||'Chưa gắn đợt'}</option>)}</select>:<strong>{team.nameTeam} · {team.defensePeriodName||'Chưa gắn đợt'}</strong>}</div>}</div>
    {error&&!modal&&<div className="workflow-error page-error"><AlertCircle size={17}/>{error}</div>}{student&&<section className="milestone-grid">{loading?<State/>:milestones.map((m)=>{const latest=latestByMilestone.get(m.milestoneId);const approved=latest?.status==='APPROVED';const timing=milestoneTiming(m);const canSubmit=m.status==='OPEN'&&!approved&&!timing.notStarted&&(!timing.expired||m.allowLateSubmission);const statusLabel=m.status!=='OPEN'?'Đã đóng':timing.notStarted?'Chưa bắt đầu':timing.expired&&m.allowLateSubmission?'Đang nhận bài muộn':timing.expired?'Đã hết hạn':'Đang nhận bài';return <article key={m.milestoneId}><header><span className={`workflow-status ${m.status.toLowerCase()} ${timing.expired?'expired':''}`}>{statusLabel}</span><small>{m.required?'Bắt buộc':'Tùy chọn'}</small></header><h3>{m.milestoneName}</h3><p>{m.description||'Không có mô tả.'}</p><div className="milestone-meta"><span>Hạn nộp <strong>{formatDate(m.deadline)}</strong></span><span>Nộp muộn <strong>{m.allowLateSubmission?'Cho phép':'Không cho phép'}</strong></span><span>Định dạng <strong>{(m.allowedFileTypes||[]).join(', ')||'Không giới hạn'}</strong></span></div>{latest&&<button className="latest-submission" onClick={()=>openDetail(latest)}><FileText size={16}/><span><strong>{STATUS[latest.status]}</strong><small>Phiên bản {latest.version} · {latest.fileName}</small></span></button>}<footer>{approved?<div className="submission-approved-note"><Check size={15}/> Bài nộp đã được phê duyệt</div>:canSubmit?<button className={`secondary-button ${timing.expired?'late-submit-button':''}`} onClick={()=>{setModal({type:'upload',milestone:m});setError('');}}> <Upload size={15}/> {timing.expired?'Nộp muộn':latest?'Nộp phiên bản mới':'Nộp bài'}</button>:<div className="submission-closed-note"><AlertCircle size={15}/> {timing.notStarted?'Chưa đến thời gian nộp':timing.expired&&!m.allowLateSubmission?'Đã hết hạn và không cho phép nộp muộn':'Mốc tiến độ đã đóng'}</div>}</footer></article>})}</section>}
    <section className="workflow-panel submissions-panel"><div className="workflow-toolbar"><label><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tìm bài nộp, milestone hoặc nhóm..."/></label><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{loading?<State/>:filtered.length===0?<div className="workflow-state"><FileText/><strong>Chưa có bài nộp phù hợp.</strong></div>:<div className="workflow-table"><table><thead><tr><th>Bài nộp</th>{!student&&<th>Nhóm</th>}<th>Người nộp</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.submissionId}><td><strong>{row.fileName}</strong><small>{row.milestoneName} · Phiên bản {row.version}</small></td>{!student&&<td>{row.teamName}</td>}<td>{row.submittedByName}<small>{row.studentCode}</small></td><td>{formatDate(row.submittedAt)}<small>{row.late?'Nộp muộn':'Đúng hạn'}</small></td><td><span className={`workflow-status ${row.status.toLowerCase()}`}>{STATUS[row.status]}</span></td><td><div className="workflow-actions"><button title="Chi tiết" onClick={()=>openDetail(row)}><Eye size={15}/></button><button title="Tải tệp" onClick={()=>download(row)}><Download size={15}/></button>{student&&row.status==='SUBMITTED'&&<button className="danger" onClick={()=>withdraw(row)}><X size={15}/></button>}</div></td></tr>)}</tbody></table></div>}</section>
    {modal?.type==='upload'&&<div className="modal-backdrop"><section className="workflow-modal compact"><header><div><span>NỘP BÁO CÁO</span><h3>{modal.milestone.milestoneName}</h3></div><button onClick={()=>setModal(null)}><X size={19}/></button></header><form onSubmit={upload}><label className="file-drop"><Upload/><strong>{file?.name||'Chọn tệp bài nộp'}</strong><small>{file?formatSize(file.size):`Cho phép: ${(modal.milestone.allowedFileTypes||[]).join(', ')||'các tệp an toàn'}`}</small><input type="file" accept={fileAccept(modal.milestone)} onChange={(e)=>chooseFile(e.target.files?.[0]||null)}/></label><label>Ghi chú<textarea value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Nội dung phiên bản hoặc lưu ý cho giảng viên..."/></label>{error&&<div className="workflow-error"><AlertCircle size={16}/>{error}</div>}<footer><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Hủy</button><button className="primary-button" disabled={saving||!file}>{saving?'Đang tải lên...':'Xác nhận nộp bài'}</button></footer></form></section></div>}
    {modal?.type==='detail'&&<div className="modal-backdrop"><section className={`submission-detail ${previewOpen?'submission-preview-expanded':''}`}><header><div><span>CHI TIẾT BÀI NỘP</span><h3>{modal.row.fileName}</h3></div><button onClick={closeDetail}><X size={19}/></button></header><div className="submission-body">
      <div className="submission-summary"><div><span>Milestone</span><strong>{modal.row.milestoneName}</strong></div><div><span>Nhóm</span><strong>{modal.row.teamName}</strong></div><div><span>Người nộp</span><strong>{modal.row.submittedByName||'Chưa xác định'}{modal.row.studentCode?` · ${modal.row.studentCode}`:''}</strong></div><div><span>Phiên bản</span><strong>{modal.row.version}</strong></div><div><span>Trạng thái</span><strong>{STATUS[modal.row.status]}</strong></div><div><span>Dung lượng</span><strong>{formatSize(modal.row.fileSize)}</strong></div><div className="submission-summary-wide"><span>Thời gian nộp</span><strong>{formatDate(modal.row.submittedAt)}</strong></div></div>
      {modal.row.note&&<div className="submission-note"><strong>Ghi chú của sinh viên</strong><p>{modal.row.note}</p></div>}
      <div className="submission-file-actions">{!student&&<button className="preview-wide" onClick={()=>previewSubmission(modal.row)} disabled={previewLoading}>{previewLoading?<LoaderCircle className="spin" size={17}/>:<Eye size={17}/>} {previewLoading?'Đang tải bản xem trước...':'Xem trước tệp'}</button>}<button className="download-wide" onClick={()=>download(modal.row)}><Download size={17}/> Tải tệp {modal.row.fileName}</button></div>
      {!student&&previewOpen&&<section className="submission-file-preview"><header><div><FileText size={16}/><strong>Xem trước {modal.row.fileName}</strong></div><button type="button" onClick={resetPreview} aria-label="Đóng bản xem trước"><X size={16}/></button></header>{previewLoading?<div className="submission-preview-state"><LoaderCircle className="spin" size={25}/><span>Đang tải tệp PDF...</span></div>:previewError?<div className="submission-preview-state error"><AlertCircle size={24}/><span>{previewError}</span></div>:previewSource?<iframe src={previewSource} title={`Xem trước ${modal.row.fileName}`}/>:null}</section>}
      <section className="comment-section"><h4><MessageSquare size={17}/> Nhận xét ({comments.length})</h4><div className="comment-list">{comments.length?comments.map(c=><article key={c.commentId}><div className="comment-heading"><div><strong>{c.lecturerName||c.authorUsername||'Người dùng'}</strong><span className={`comment-type ${String(c.commentType||'COMMENT').toLowerCase()}`}>{commentTypeLabel(c.commentType)}</span></div>{canManageComment(c)&&editingCommentId!==c.commentId&&<div className="comment-actions"><button title="Sửa nhận xét" onClick={()=>startEditComment(c)}><Edit3 size={13}/></button><button className="danger" title="Xóa nhận xét" onClick={()=>setCommentConfirm(c)}><Trash2 size={13}/></button></div>}</div>{editingCommentId===c.commentId?<div className="comment-editor"><textarea autoFocus value={editingContent} onChange={(e)=>setEditingContent(e.target.value)}/><div><button title="Hủy sửa" onClick={()=>{setEditingCommentId(null);setEditingContent('');}}><X size={14}/></button><button className="save" title="Lưu nhận xét" disabled={saving||!editingContent.trim()} onClick={()=>updateComment(c)}><Check size={14}/></button></div></div>:<p>{c.content}</p>}<small>{formatDate(c.createdAt)}{c.edited?' · Đã sửa':''}</small></article>):<p className="empty-comment">Chưa có nhận xét.</p>}</div>{!student&&<div className="comment-input"><textarea value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Nhập nhận xét cho bài nộp..."/><button title="Gửi nhận xét" onClick={addComment} disabled={saving||!comment.trim()}><Send size={16}/></button></div>}</section>{error&&<div className="workflow-error"><AlertCircle size={16}/>{error}</div>}
    </div><footer>{!student&&<div className="review-actions">{modal.row.status==='SUBMITTED'&&<button onClick={()=>workflow('review')}>Bắt đầu duyệt</button>}{['SUBMITTED','UNDER_REVIEW'].includes(modal.row.status)&&<><button className="warning" onClick={()=>workflow('revise')}>Yêu cầu sửa</button><button className="danger" onClick={()=>workflow('reject')}>Từ chối</button><button className="success" onClick={()=>workflow('approve')}>Phê duyệt</button></>}</div>}<button className="secondary-button" onClick={closeDetail}>Đóng</button></footer></section></div>}
    <ConfirmModal open={Boolean(commentConfirm)} type="delete" title="Xóa nhận xét?" message="Nhận xét này sẽ bị xóa khỏi bài nộp và không thể khôi phục." confirmLabel="Xóa nhận xét" loading={saving} onCancel={()=>setCommentConfirm(null)} onConfirm={deleteComment}/></div>;
}
function State(){return <div className="workflow-state"><LoaderCircle className="spin"/><strong>Đang tải dữ liệu...</strong></div>} function formatDate(v){return formatDateTimeDisplay(v)} function formatSize(n=0){if(!n)return'—';if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function commentTypeLabel(type){return {COMMENT:'Nhận xét',REVISION_REQUEST:'Yêu cầu chỉnh sửa',APPROVAL:'Phê duyệt',REJECTION:'Từ chối'}[type]||'Nhận xét'}
function milestoneTiming(milestone){const now=Date.now();const start=milestone.startAt?new Date(milestone.startAt).getTime():null;const deadline=milestone.deadline?new Date(milestone.deadline).getTime():null;return {notStarted:start!==null&&now<start,expired:deadline!==null&&now>deadline};}
function fileAccept(milestone){return (milestone.allowedFileTypes||[]).map((type)=>`.${String(type).replace(/^\./,'')}`).join(',');}
function validateSubmissionFile(milestone,selected){const extension=selected.name.includes('.')?selected.name.split('.').pop().toLowerCase():'';const allowed=(milestone.allowedFileTypes||[]).map((type)=>String(type).replace(/^\./,'').toLowerCase());if(allowed.length&&!allowed.includes(extension))return `Tệp .${extension||'không xác định'} không được hỗ trợ. Chỉ chấp nhận: ${allowed.map((type)=>`.${type}`).join(', ')}.`;if(milestone.maxFileSize&&selected.size>milestone.maxFileSize)return `Dung lượng tệp vượt quá giới hạn ${formatSize(milestone.maxFileSize)}.`;return '';}
