package com.graduration.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ErrorCode {
    //    Lỗi cấu hình
    UKNOWN_ERROR(9999, "Hệ thống đang gặp lỗi. Vui lòng thử lại sau", HttpStatus.INTERNAL_SERVER_ERROR),
    PERMISSION_INVALID(1001, "Permission Invalid", HttpStatus.NOT_FOUND),
    PERMISION_NAME_INVALID(1002, "Name Perission Invalid", HttpStatus.NOT_FOUND),
    PERMISSION_NOT_BLANK(1003, "Permission Not Blank", HttpStatus.BAD_REQUEST),
    PERMISSION_IS_EXITED(1004, "Permission is exited", HttpStatus.CONFLICT),
    ROLE_INVALID(1005, "Role Invalid", HttpStatus.NOT_FOUND),
    ROLE_NAME_INVALID(1006, "Role Name Invalid", HttpStatus.NOT_FOUND),
    ROLE_NOT_BLANK(1007, "Role is not blank", HttpStatus.BAD_REQUEST),
    ROLE_IS_EXITED(1008, "Role is exited", HttpStatus.CONFLICT),
    ROLE_NOT_FOUND(1009, "role not found", HttpStatus.CONFLICT),
    PERMISSION_NOT_FOUND(1010, "Permission not found", HttpStatus.CONFLICT),
    STATUS_NOT_FOUND(1011, "Status not found", HttpStatus.CONFLICT),
    INVALID_KEY(1012, "Dữ liệu gửi lên không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(1013, "Invalid password", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(1014, "invalid email", HttpStatus.BAD_REQUEST),
    EMAIL_IS_REQUIRED(1015, "email is required", HttpStatus.BAD_REQUEST),
    USERNAME_IS_EXITED(1016, "User name is exited", HttpStatus.BAD_REQUEST),
    EMAIL_VERIFIED_EXITED(1017, "Email is exited", HttpStatus.BAD_REQUEST),
    USER_EXITED(1018, "User is exited", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1019, "Authentication is required or token is invalid", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1020, "Tên đăng nhập hoặc mật khẩu không chính xác", HttpStatus.FORBIDDEN),
    USER_NOT_FOUND(1021, "User not found by username, lecturer code or student code", HttpStatus.NOT_FOUND),
    StATUS_BANNED(1022, "state already implemented", HttpStatus.BAD_REQUEST),
    OTP_INVALID(1023, "OTP Invalid", HttpStatus.BAD_REQUEST),
    OTP_EXPIRED(1024, "OTP expired", HttpStatus.BAD_REQUEST),
    INVALID_USERNAME(1025, "A username, lecturer code or student code is required", HttpStatus.BAD_REQUEST),
    ACCESS_DENIED(1026, "You do not have permission", HttpStatus.FORBIDDEN),
    PASSWORD_NOT_BLANK(1027, "password not blank", HttpStatus.BAD_REQUEST),
    USERNAME_NOT_BLANK(1028, "username not blank", HttpStatus.BAD_REQUEST),
    LECTURER_NOT_BLANK(1029, "lecture not blank", HttpStatus.BAD_REQUEST),
    FULLNAME_NOT_BLANK(1030, "full name lecturer not blank", HttpStatus.BAD_REQUEST),
    INVALID_PHONE(1031, "invalid phone number", HttpStatus.BAD_REQUEST),
    PHONE_IS_EXITED(1032, "phone number is exited", HttpStatus.CONFLICT),
    LECTURER_CODE_IS_EXITED(1033, "lecturer code is exited", HttpStatus.CONFLICT),
    INVALID_EXCEL_FILE(1034, "invalid or empty Excel file", HttpStatus.BAD_REQUEST),
    EXCEL_ROW_INVALID(1035, "Excel row data is invalid", HttpStatus.BAD_REQUEST),
    STUDENT_NOT_BLANK(1036, "Student not blank", HttpStatus.BAD_REQUEST),
    CLASS_CODE_NOT_BLANK(1037, "Class Code not blank", HttpStatus.BAD_REQUEST),
    CLASS_NAME_NOT_BLANK(1038, "Class Name not blank", HttpStatus.BAD_REQUEST),
    MAJOR_ID_NOT_BLANK(1039, "Major id not blank", HttpStatus.BAD_REQUEST),
    AMBIGUOUS_LOGIN_IDENTIFIER(1040, "Login identifier matches multiple accounts", HttpStatus.CONFLICT),
    TEAM_NOT_FOUND(1041, "Team not found", HttpStatus.NOT_FOUND),
    TEAM_NAME_NOT_BLANK(1042, "Team name not blank", HttpStatus.BAD_REQUEST),
    TEAM_ALREADY_EXISTS(1043, "Team name already exists", HttpStatus.CONFLICT),
    STUDENT_ALREADY_IN_TEAM(1044, "Student already belongs to a team", HttpStatus.CONFLICT),
    TOPIC_ALREADY_ASSIGNED(1045, "Topic already belongs to another team", HttpStatus.CONFLICT),
    ACADEMIC_YEAR_NOT_FOUND(1046, "Academic year not found", HttpStatus.NOT_FOUND),
    ACADEMIC_YEAR_NOT_BLANK(1047, "Academic year not blank", HttpStatus.BAD_REQUEST),
    ACADEMIC_YEAR_INVALID(1048, "Academic year must have format YYYY-YYYY", HttpStatus.BAD_REQUEST),
    ACADEMIC_YEAR_ALREADY_EXISTS(1049, "Academic year already exists", HttpStatus.CONFLICT),
    ACADEMIC_YEAR_IN_USE(1050, "Academic year contains defense data and cannot be deleted", HttpStatus.CONFLICT),
    DEFENSE_PERIOD_NOT_FOUND(1051, "Defense period not found", HttpStatus.NOT_FOUND),
    DEFENSE_PERIOD_NAME_NOT_BLANK(1052, "Defense period name not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_PERIOD_INVALID(1053, "Defense period data is invalid", HttpStatus.BAD_REQUEST),
    DEFENSE_PERIOD_INVALID_DATE(1054, "End date must not be before start date", HttpStatus.BAD_REQUEST),
    DEFENSE_PERIOD_ALREADY_EXISTS(1055, "Defense period already exists in this academic year", HttpStatus.CONFLICT),
    DEFENSE_PERIOD_IN_USE(
            1056, "Defense period contains topics or milestones and cannot be deleted", HttpStatus.CONFLICT),
    START_DATE_NOT_BLANK(1057, "Start date not blank", HttpStatus.BAD_REQUEST),
    END_DATE_NOT_BLANK(1058, "End date not blank", HttpStatus.BAD_REQUEST),
    LIBRARY_TOPIC_NOT_FOUND(1059, "Library topic not found", HttpStatus.NOT_FOUND),
    LIBRARY_TOPIC_TITLE_NOT_BLANK(1060, "Library topic title not blank", HttpStatus.BAD_REQUEST),
    LIBRARY_TOPIC_ALREADY_EXISTS(1061, "Library topic title already exists", HttpStatus.CONFLICT),
    TEMPLATE_NOT_FOUND(1062, "Template not found", HttpStatus.NOT_FOUND),
    TEMPLATE_NAME_NOT_BLANK(1063, "Template name not blank", HttpStatus.BAD_REQUEST),
    TEMPLATE_ALREADY_EXISTS(1064, "Template name already exists", HttpStatus.CONFLICT),
    AUDIT_LOG_NOT_FOUND(1065, "Audit log not found", HttpStatus.NOT_FOUND),
    AUDIT_LOG_ACTION_NOT_BLANK(1066, "Audit log action not blank", HttpStatus.BAD_REQUEST),
    AUDIT_LOG_USER_ID_NOT_BLANK(1067, "Audit log user id not blank", HttpStatus.BAD_REQUEST),
    CLASS_IN_USE(1068, "Class contains students and cannot be deleted", HttpStatus.CONFLICT),
    MAJOR_IN_USE(1069, "Major contains classes and cannot be deleted", HttpStatus.CONFLICT),
    ENDPOINT_NOT_FOUND(1070, "Endpoint not found", HttpStatus.NOT_FOUND),
    METHOD_NOT_ALLOWED(1071, "HTTP method not allowed", HttpStatus.METHOD_NOT_ALLOWED),
    DATA_CONFLICT(1072, "Data conflicts with an existing record", HttpStatus.CONFLICT),
    ACCOUNT_INACTIVE(1073, "Tài khoản đã dừng hoạt động", HttpStatus.UNAUTHORIZED),
    TOPIC_NOT_FOUND(1074, "Topic not found", HttpStatus.NOT_FOUND),
    TOPIC_INVALID(1075, "Topic data is invalid", HttpStatus.BAD_REQUEST),
    TOPIC_TITLE_NOT_BLANK(1076, "Topic title not blank", HttpStatus.BAD_REQUEST),
    TOPIC_CATEGORY_NOT_BLANK(1077, "Topic category not blank", HttpStatus.BAD_REQUEST),
    TOPIC_ALREADY_EXISTS(1078, "Topic title already exists in this defense period", HttpStatus.CONFLICT),
    TOPIC_IN_USE(1079, "Topic is already used and cannot be deleted", HttpStatus.CONFLICT),
    TOPIC_OPERATION_NOT_ALLOWED(1080, "Operation is not allowed for the current topic status", HttpStatus.CONFLICT),
    TOPIC_REJECTION_REASON_NOT_BLANK(1081, "Rejection reason not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_PERIOD_FINISHED(1082, "Defense period is already finished", HttpStatus.CONFLICT),
    TOPIC_NOT_AVAILABLE(1083, "Topic is not available for selection", HttpStatus.CONFLICT),
    TEAM_ALREADY_HAS_TOPIC(1084, "Team already has a topic", HttpStatus.CONFLICT),
    MILESTONE_NOT_FOUND(1085, "Milestone not found", HttpStatus.NOT_FOUND),
    MILESTONE_NAME_NOT_BLANK(1086, "Milestone name not blank", HttpStatus.BAD_REQUEST),
    MILESTONE_TYPE_NOT_BLANK(1087, "Milestone type not blank", HttpStatus.BAD_REQUEST),
    MILESTONE_START_AT_NOT_BLANK(1088, "Milestone start time not blank", HttpStatus.BAD_REQUEST),
    MILESTONE_DEADLINE_NOT_BLANK(1089, "Milestone deadline not blank", HttpStatus.BAD_REQUEST),
    MILESTONE_INVALID_DATE(1090, "Milestone start time must be before its deadline", HttpStatus.BAD_REQUEST),
    MILESTONE_OUTSIDE_DEFENSE_PERIOD(1091, "Milestone time is outside the defense period", HttpStatus.BAD_REQUEST),
    MILESTONE_ALREADY_EXISTS(1092, "Milestone name already exists in this defense period", HttpStatus.CONFLICT),
    MILESTONE_OPERATION_NOT_ALLOWED(
            1093, "Operation is not allowed for the current milestone status", HttpStatus.CONFLICT),
    MILESTONE_IN_USE(1094, "Milestone contains submissions and cannot be deleted", HttpStatus.CONFLICT),
    MILESTONE_MAX_FILE_SIZE_INVALID(1095, "Milestone max file size must be greater than zero", HttpStatus.BAD_REQUEST),
    SUBMISSION_NOT_FOUND(1096, "Submission not found", HttpStatus.NOT_FOUND),
    SUBMISSION_FILE_REQUIRED(1097, "Submission file is required", HttpStatus.BAD_REQUEST),
    SUBMISSION_FILE_TOO_LARGE(1098, "Submission file exceeds the milestone limit", HttpStatus.BAD_REQUEST),
    SUBMISSION_FILE_TYPE_NOT_ALLOWED(1099, "Submission file type is not allowed", HttpStatus.BAD_REQUEST),
    SUBMISSION_NOT_OPEN(1100, "Milestone is not open for submission", HttpStatus.CONFLICT),
    SUBMISSION_NOT_STARTED(1101, "Submission period has not started", HttpStatus.CONFLICT),
    SUBMISSION_DEADLINE_PASSED(1102, "Submission deadline has passed", HttpStatus.CONFLICT),
    SUBMISSION_OPERATION_NOT_ALLOWED(
            1103, "Operation is not allowed for the current submission status", HttpStatus.CONFLICT),
    SUBMISSION_ALREADY_APPROVED(1104, "The latest submission is already approved", HttpStatus.CONFLICT),
    SUBMISSION_PERIOD_MISMATCH(1105, "Team does not belong to the milestone defense period", HttpStatus.CONFLICT),
    STUDENT_PROFILE_NOT_FOUND(1106, "Student profile not found for current account", HttpStatus.NOT_FOUND),
    LECTURER_PROFILE_NOT_FOUND(1107, "Lecturer profile not found for current account", HttpStatus.NOT_FOUND),
    SUBMISSION_COMMENT_NOT_BLANK(1108, "Submission comment not blank", HttpStatus.BAD_REQUEST),
    FILE_STORAGE_ERROR(1109, "Could not store or read submission file", HttpStatus.INTERNAL_SERVER_ERROR),
    COMMENT_NOT_FOUND(1110, "Comment not found", HttpStatus.NOT_FOUND),
    COMMENT_OPERATION_NOT_ALLOWED(1111, "Operation is not allowed for this comment", HttpStatus.CONFLICT),
    SCORE_CRITERION_NOT_FOUND(1112, "Score criterion not found", HttpStatus.NOT_FOUND),
    SCORE_CRITERION_CODE_NOT_BLANK(1113, "Score criterion code not blank", HttpStatus.BAD_REQUEST),
    SCORE_CRITERION_NAME_NOT_BLANK(1114, "Score criterion name not blank", HttpStatus.BAD_REQUEST),
    SCORE_CRITERION_MAX_SCORE_INVALID(1115, "Score criterion max score is invalid", HttpStatus.BAD_REQUEST),
    SCORE_CRITERION_WEIGHT_INVALID(1116, "Score criterion weight must be between 0 and 100", HttpStatus.BAD_REQUEST),
    SCORE_CRITERION_ALREADY_EXISTS(
            1117, "Score criterion code already exists in this defense period", HttpStatus.CONFLICT),
    SCORE_CRITERION_IN_USE(1118, "Score criterion is already used", HttpStatus.CONFLICT),
    SCORE_CRITERIA_WEIGHT_INVALID(1119, "Active score criterion weights must total 100", HttpStatus.CONFLICT),
    SCORE_NOT_FOUND(1120, "Score not found", HttpStatus.NOT_FOUND),
    SCORE_DETAILS_NOT_EMPTY(1121, "Score details not empty", HttpStatus.BAD_REQUEST),
    SCORE_VALUE_INVALID(1122, "Score value is outside the criterion range", HttpStatus.BAD_REQUEST),
    SCORE_CRITERIA_MISMATCH(1123, "Score must contain every active criterion exactly once", HttpStatus.BAD_REQUEST),
    SCORE_OPERATION_NOT_ALLOWED(1124, "Operation is not allowed for the current score status", HttpStatus.CONFLICT),
    SCORE_STUDENT_TOPIC_MISMATCH(1125, "Student does not belong to the topic team", HttpStatus.CONFLICT),
    TOPIC_SUPERVISOR_NOT_FOUND(1126, "Topic supervisor assignment not found", HttpStatus.NOT_FOUND),
    SUPERVISOR_ROLE_NOT_BLANK(1127, "Supervisor role not blank", HttpStatus.BAD_REQUEST),
    TOPIC_SUPERVISOR_ALREADY_ASSIGNED(1128, "Lecturer is already assigned to this topic", HttpStatus.CONFLICT),
    TOPIC_PRIMARY_SUPERVISOR_ALREADY_EXISTS(
            1129, "Topic already has an active primary supervisor", HttpStatus.CONFLICT),
    SUPERVISOR_ASSIGNMENT_NOT_ACTIVE(1130, "Supervisor assignment is not active", HttpStatus.CONFLICT),
    SUPERVISOR_DEACTIVATION_REASON_NOT_BLANK(1131, "Deactivation reason not blank", HttpStatus.BAD_REQUEST),
    LECTURER_INACTIVE(1132, "Lecturer account is inactive", HttpStatus.CONFLICT),
    TOPIC_SUPERVISOR_LIMIT_REACHED(1133, "Lecturer has reached the topic supervision limit", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_NOT_FOUND(1134, "Defense committee not found", HttpStatus.NOT_FOUND),
    COMMITTEE_MEMBER_NOT_FOUND(1135, "Committee member assignment not found", HttpStatus.NOT_FOUND),
    COMMITTEE_MEMBER_ROLE_NOT_BLANK(1136, "Committee member role not blank", HttpStatus.BAD_REQUEST),
    COMMITTEE_MEMBER_ALREADY_ASSIGNED(1137, "Lecturer is already assigned to this committee", HttpStatus.CONFLICT),
    COMMITTEE_CHAIRPERSON_ALREADY_EXISTS(1138, "Committee already has an active chairperson", HttpStatus.CONFLICT),
    COMMITTEE_SECRETARY_ALREADY_EXISTS(1139, "Committee already has an active secretary", HttpStatus.CONFLICT),
    COMMITTEE_MEMBER_NOT_ACTIVE(1140, "Committee member assignment is not active", HttpStatus.CONFLICT),
    COMMITTEE_MEMBER_DEACTIVATION_REASON_NOT_BLANK(
            1141, "Committee member deactivation reason not blank", HttpStatus.BAD_REQUEST),
    COMMITTEE_PERIOD_MISMATCH(1142, "Committee is not attached to a valid defense period", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_NAME_NOT_BLANK(1143, "Defense committee name not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_COMMITTEE_ALREADY_EXISTS(1144, "Defense committee name already exists in this period", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_NOT_READY(1145, "Defense committee does not have a valid member structure", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_OPERATION_NOT_ALLOWED(
            1146, "Operation is not allowed for the current committee status", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_IN_USE(1147, "Defense committee is already in use", HttpStatus.CONFLICT),
    DEFENSE_COMMITTEE_DEACTIVATION_REASON_NOT_BLANK(
            1148, "Defense committee deactivation reason not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_NOT_FOUND(1149, "Defense schedule not found", HttpStatus.NOT_FOUND),
    DEFENSE_SCHEDULE_DATE_NOT_BLANK(1150, "Defense date not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_START_TIME_NOT_BLANK(1151, "Defense start time not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_END_TIME_NOT_BLANK(1152, "Defense end time not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_ROOM_NOT_BLANK(1153, "Defense room not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_LOCATION_NOT_BLANK(1154, "Defense location not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_INVALID_TIME(1155, "Defense schedule time is invalid", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_OUTSIDE_PERIOD(1156, "Defense date is outside the defense period", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_CONFLICT(1157, "Defense schedule contains one or more conflicts", HttpStatus.CONFLICT),
    DEFENSE_SCHEDULE_OPERATION_NOT_ALLOWED(
            1158, "Operation is not allowed for the current schedule status", HttpStatus.CONFLICT),
    DEFENSE_SCHEDULE_REASON_NOT_BLANK(1159, "Defense schedule reason not blank", HttpStatus.BAD_REQUEST),
    DEFENSE_SCHEDULE_TOPIC_NOT_ELIGIBLE(1160, "Topic is not eligible for defense scheduling", HttpStatus.CONFLICT),
    DEFENSE_SCHEDULE_NOT_FINISHED(1161, "Defense session has not finished yet", HttpStatus.CONFLICT),
    REVIEW_ASSIGNMENT_NOT_FOUND(1162, "Review assignment not found", HttpStatus.NOT_FOUND),
    REVIEW_DEADLINE_NOT_BLANK(1163, "Review deadline not blank", HttpStatus.BAD_REQUEST),
    REVIEW_DEADLINE_INVALID(1164, "Review deadline is invalid", HttpStatus.BAD_REQUEST),
    REVIEW_ASSIGNMENT_ALREADY_EXISTS(1165, "Lecturer is already reviewing this topic", HttpStatus.CONFLICT),
    REVIEW_ASSIGNMENT_LIMIT_REACHED(1166, "Review assignment limit has been reached", HttpStatus.CONFLICT),
    REVIEW_SUPERVISOR_CONFLICT(1167, "Topic supervisor cannot review the same topic", HttpStatus.CONFLICT),
    REVIEW_OPERATION_NOT_ALLOWED(1168, "Operation is not allowed for the current review status", HttpStatus.CONFLICT),
    REVIEW_COMMENT_NOT_BLANK(1169, "Review comment not blank", HttpStatus.BAD_REQUEST),
    REVIEW_RECOMMENDATION_NOT_BLANK(1170, "Review recommendation not blank", HttpStatus.BAD_REQUEST),
    REVIEW_CANCEL_REASON_NOT_BLANK(1171, "Review cancellation reason not blank", HttpStatus.BAD_REQUEST),
    REVIEW_NOT_APPROVED(1172, "Topic does not have an approved review", HttpStatus.CONFLICT),
    IMPORT_DATA_ALREADY_EXISTS(1173, "Dữ liệu import đã có trong hệ thống", HttpStatus.CONFLICT);

    ErrorCode(int code, String mesage, HttpStatusCode statusCode) {
        this.code = code;
        this.mesage = mesage;
        this.statusCode = statusCode;
    }

    int code;
    String mesage;
    HttpStatusCode statusCode;
}
