import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Archive, BookOpen, CalendarDays, ChevronDown, Eye, Inbox, LoaderCircle, Search, Users, X } from 'lucide-react';
import ResourceService from '../../services/ResourceService.jsx';
import API_ENDPOINTS from '../../config/endpoints.js';
import getApiErrorMessage from '../../utils/apiError.js';
import '../../style/ProjectHistory.scss';

const statusLabels = { DRAFT: 'Bản nháp', PENDING_APPROVAL: 'Chờ phê duyệt', APPROVED: 'Đã phê duyệt', REJECTED: 'Đã từ chối', REGISTERED: 'Đã đăng ký', PENDING: 'Chờ diễn ra', ONGOING: 'Đang diễn ra', FINISHED: 'Đã kết thúc' };

export default function ProjectHistoryPage() {
  const [years, setYears] = useState([]); const [periods, setPeriods] = useState([]); const [topics, setTopics] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const [yearFilter, setYearFilter] = useState(''); const [scope, setScope] = useState('all'); const [expandedYears, setExpandedYears] = useState(new Set());
  const [expandedPeriods, setExpandedPeriods] = useState(new Set()); const [detail, setDetail] = useState(null); const [detailLoading, setDetailLoading] = useState(false);

  const load = async () => { setLoading(true); setError(''); try { const [yearItems, periodItems, topicItems] = await Promise.all([ResourceService.getAll(API_ENDPOINTS.academicYears.list), ResourceService.getAll(API_ENDPOINTS.defensePeriods.list), ResourceService.getAll(API_ENDPOINTS.topics.list)]); setYears(yearItems); setPeriods(periodItems); setTopics(topicItems); setExpandedYears(new Set(yearItems.slice(0, 1).map((item) => item.academicId))); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Không thể tải kho lịch sử đồ án.')); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);

  const archive = useMemo(() => {
    const term = normalize(query);
    return [...years].sort((a, b) => String(b.academicYear).localeCompare(String(a.academicYear))).filter((year) => !yearFilter || String(year.academicId) === yearFilter).map((year) => {
      const yearPeriods = periods.filter((period) => String(period.academicId) === String(year.academicId)).filter((period) => scope !== 'finished' || period.status === 'FINISHED').map((period) => {
        const periodTopics = topics.filter((topic) => String(topic.defensePeriodId) === String(period.defensePeriodId)).filter((topic) => !term || normalize(`${topic.title} ${topic.technology} ${topic.teamName} ${period.periodName} ${year.academicYear}`).includes(term));
        return { ...period, topics: periodTopics };
      }).filter((period) => !term || period.topics.length > 0 || normalize(`${period.periodName} ${year.academicYear}`).includes(term));
      return { ...year, periods: yearPeriods };
    }).filter((year) => year.periods.length > 0 || (!term && scope === 'all'));
  }, [years, periods, topics, query, yearFilter, scope]);

  const totalPeriods = archive.reduce((sum, year) => sum + year.periods.length, 0); const totalTopics = archive.reduce((sum, year) => sum + year.periods.reduce((count, period) => count + period.topics.length, 0), 0);
  const toggle = (setter, value) => setter((current) => { const next = new Set(current); if (next.has(value)) next.delete(value); else next.add(value); return next; });
  const openTopic = async (topic) => { setDetail(topic); setDetailLoading(true); try { setDetail(await ResourceService.getOne(API_ENDPOINTS.topics.detail(topic.topicId))); } catch { setDetail(topic); } finally { setDetailLoading(false); } };

  return <div className="history-page page-stack">
    <section className="page-title-row"><div><span className="page-kicker">KHO LƯU TRỮ ĐỒ ÁN</span><h2>Lịch sử năm học và đợt bảo vệ</h2><p>Tra cứu tập trung các đợt bảo vệ và đề tài đã được lưu trong hệ thống.</p></div><div className="history-summary"><span><strong>{archive.length}</strong>Năm học</span><span><strong>{totalPeriods}</strong>Đợt bảo vệ</span><span><strong>{totalTopics}</strong>Đề tài</span></div></section>
    <section className="history-toolbar panel"><label><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tên đề tài, công nghệ, nhóm hoặc đợt bảo vệ..." />{query && <button onClick={() => setQuery('')}><X size={15} /></button>}</label><select value={yearFilter} onChange={(event) => setYearFilter(event.target.value)}><option value="">Tất cả năm học</option>{[...years].sort((a, b) => String(b.academicYear).localeCompare(String(a.academicYear))).map((year) => <option key={year.academicId} value={year.academicId}>{year.academicYear}</option>)}</select><select value={scope} onChange={(event) => setScope(event.target.value)}><option value="all">Tất cả đợt bảo vệ</option><option value="finished">Chỉ đợt đã kết thúc</option></select></section>
    {loading ? <HistoryState icon={LoaderCircle} text="Đang tổng hợp dữ liệu lịch sử..." spin /> : error ? <HistoryState icon={AlertCircle} text={error} action={load} /> : archive.length === 0 ? <HistoryState icon={Inbox} text="Không tìm thấy dữ liệu lịch sử phù hợp." /> : <section className="history-tree">{archive.map((year) => { const openYear = expandedYears.has(year.academicId); const yearTopicCount = year.periods.reduce((sum, period) => sum + period.topics.length, 0); return <article className={`history-year ${openYear ? 'open' : ''}`} key={year.academicId}><button className="history-year-head" onClick={() => toggle(setExpandedYears, year.academicId)}><span className="history-icon"><Archive size={21} /></span><span><small>NĂM HỌC</small><strong>{year.academicYear}</strong><em>{year.description || 'Kho dữ liệu đồ án tốt nghiệp'}</em></span><span className="history-counts"><b>{year.periods.length} đợt</b><b>{yearTopicCount} đề tài</b></span><ChevronDown size={20} /></button>{openYear && <div className="history-periods">{year.periods.length ? year.periods.map((period) => { const openPeriod = expandedPeriods.has(period.defensePeriodId) || Boolean(query); return <section className={`history-period ${openPeriod ? 'open' : ''}`} key={period.defensePeriodId}><button className="history-period-head" onClick={() => toggle(setExpandedPeriods, period.defensePeriodId)}><CalendarDays size={19} /><span><strong>{period.periodName}</strong><small>{formatDate(period.startDate)} – {formatDate(period.endDate)} · {period.projectType || 'Đồ án tốt nghiệp'}</small></span><span className={`history-status ${String(period.status).toLowerCase()}`}>{statusLabels[period.status] || period.status}</span><b>{period.topics.length} đề tài</b><ChevronDown size={18} /></button>{openPeriod && <div className="history-topics">{period.topics.length ? period.topics.map((topic) => <article key={topic.topicId}><span className="topic-number">#{topic.topicId}</span><div><strong>{topic.title}</strong><small>{topic.technology || 'Chưa cập nhật công nghệ'}</small></div><span><Users size={14} />{topic.teamName || 'Chưa phân nhóm'}</span><span className={`history-status ${String(topic.status).toLowerCase()}`}>{statusLabels[topic.status] || topic.status}</span><button onClick={() => openTopic(topic)}><Eye size={16} /> Xem</button></article>) : <div className="history-empty">Đợt bảo vệ chưa có đề tài.</div>}</div>}</section>; }) : <div className="history-empty">Năm học chưa có đợt bảo vệ.</div>}</div>}</article>; })}</section>}
    {detail && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setDetail(null)}><section className="history-detail" role="dialog" aria-modal="true"><header><div><span>HỒ SƠ ĐỀ TÀI LỊCH SỬ</span><h3>{detail.title}</h3></div><button onClick={() => setDetail(null)}><X size={20} /></button></header>{detailLoading ? <HistoryState icon={LoaderCircle} text="Đang tải hồ sơ đề tài..." spin /> : <div className="history-detail-body"><div className="history-detail-meta"><span><small>Năm học</small><strong>{detail.academicYear || '—'}</strong></span><span><small>Đợt bảo vệ</small><strong>{detail.defensePeriodName || '—'}</strong></span><span><small>Trạng thái</small><strong>{statusLabels[detail.status] || detail.status}</strong></span><span><small>Nhóm thực hiện</small><strong>{detail.teamName || 'Chưa phân nhóm'}</strong></span></div><section><h4><BookOpen size={18} /> Nội dung đề tài</h4><div className="history-detail-grid"><div><small>Mô tả</small><p>{detail.description || 'Chưa có mô tả.'}</p></div><div><small>Mục tiêu</small><p>{detail.objective || 'Chưa cập nhật mục tiêu.'}</p></div></div><div><small>Công nghệ sử dụng</small><p>{detail.technology || 'Chưa cập nhật.'}</p></div></section><section><h4>Thông tin lưu trữ</h4><div className="history-detail-meta"><span><small>Người tạo</small><strong>{detail.createdByName || detail.createdBy || '—'}</strong></span><span><small>Ngày tạo</small><strong>{formatDate(detail.createdAt)}</strong></span><span><small>Cập nhật gần nhất</small><strong>{formatDate(detail.updatedAt)}</strong></span></div></section></div>}<footer><button className="primary-button" onClick={() => setDetail(null)}>Đóng</button></footer></section></div>}
  </div>;
}

function HistoryState({ icon: Icon, text, action, spin }) { return <div className="history-state"><Icon className={spin ? 'spin' : ''} size={30} /><strong>{text}</strong>{action && <button onClick={action}>Thử lại</button>}</div>; }
function normalize(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('vi-VN').format(date); }
